
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `bookings` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model bookings
 * 
 */
export type bookingsModel = runtime.Types.Result.DefaultSelection<Prisma.$bookingsPayload>

export type AggregateBookings = {
  _count: BookingsCountAggregateOutputType | null
  _avg: BookingsAvgAggregateOutputType | null
  _sum: BookingsSumAggregateOutputType | null
  _min: BookingsMinAggregateOutputType | null
  _max: BookingsMaxAggregateOutputType | null
}

export type BookingsAvgAggregateOutputType = {
  id: number | null
  resource_id: number | null
  service_id: number | null
}

export type BookingsSumAggregateOutputType = {
  id: number | null
  resource_id: number | null
  service_id: number | null
}

export type BookingsMinAggregateOutputType = {
  id: number | null
  resource_id: number | null
  customer_name: string | null
  customer_phone: string | null
  customer_email: string | null
  start_time: Date | null
  end_time: Date | null
  status: $Enums.booking_status | null
  service_id: number | null
  created_at: Date | null
}

export type BookingsMaxAggregateOutputType = {
  id: number | null
  resource_id: number | null
  customer_name: string | null
  customer_phone: string | null
  customer_email: string | null
  start_time: Date | null
  end_time: Date | null
  status: $Enums.booking_status | null
  service_id: number | null
  created_at: Date | null
}

export type BookingsCountAggregateOutputType = {
  id: number
  resource_id: number
  customer_name: number
  customer_phone: number
  customer_email: number
  start_time: number
  end_time: number
  status: number
  service_id: number
  created_at: number
  _all: number
}


export type BookingsAvgAggregateInputType = {
  id?: true
  resource_id?: true
  service_id?: true
}

export type BookingsSumAggregateInputType = {
  id?: true
  resource_id?: true
  service_id?: true
}

export type BookingsMinAggregateInputType = {
  id?: true
  resource_id?: true
  customer_name?: true
  customer_phone?: true
  customer_email?: true
  start_time?: true
  end_time?: true
  status?: true
  service_id?: true
  created_at?: true
}

export type BookingsMaxAggregateInputType = {
  id?: true
  resource_id?: true
  customer_name?: true
  customer_phone?: true
  customer_email?: true
  start_time?: true
  end_time?: true
  status?: true
  service_id?: true
  created_at?: true
}

export type BookingsCountAggregateInputType = {
  id?: true
  resource_id?: true
  customer_name?: true
  customer_phone?: true
  customer_email?: true
  start_time?: true
  end_time?: true
  status?: true
  service_id?: true
  created_at?: true
  _all?: true
}

export type BookingsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which bookings to aggregate.
   */
  where?: Prisma.bookingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of bookings to fetch.
   */
  orderBy?: Prisma.bookingsOrderByWithRelationInput | Prisma.bookingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.bookingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` bookings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` bookings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned bookings
  **/
  _count?: true | BookingsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BookingsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BookingsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BookingsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BookingsMaxAggregateInputType
}

export type GetBookingsAggregateType<T extends BookingsAggregateArgs> = {
      [P in keyof T & keyof AggregateBookings]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBookings[P]>
    : Prisma.GetScalarType<T[P], AggregateBookings[P]>
}




export type bookingsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.bookingsWhereInput
  orderBy?: Prisma.bookingsOrderByWithAggregationInput | Prisma.bookingsOrderByWithAggregationInput[]
  by: Prisma.BookingsScalarFieldEnum[] | Prisma.BookingsScalarFieldEnum
  having?: Prisma.bookingsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BookingsCountAggregateInputType | true
  _avg?: BookingsAvgAggregateInputType
  _sum?: BookingsSumAggregateInputType
  _min?: BookingsMinAggregateInputType
  _max?: BookingsMaxAggregateInputType
}

export type BookingsGroupByOutputType = {
  id: number
  resource_id: number
  customer_name: string
  customer_phone: string | null
  customer_email: string | null
  start_time: Date
  end_time: Date
  status: $Enums.booking_status
  service_id: number | null
  created_at: Date
  _count: BookingsCountAggregateOutputType | null
  _avg: BookingsAvgAggregateOutputType | null
  _sum: BookingsSumAggregateOutputType | null
  _min: BookingsMinAggregateOutputType | null
  _max: BookingsMaxAggregateOutputType | null
}

type GetBookingsGroupByPayload<T extends bookingsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BookingsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BookingsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BookingsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BookingsGroupByOutputType[P]>
      }
    >
  >



export type bookingsWhereInput = {
  AND?: Prisma.bookingsWhereInput | Prisma.bookingsWhereInput[]
  OR?: Prisma.bookingsWhereInput[]
  NOT?: Prisma.bookingsWhereInput | Prisma.bookingsWhereInput[]
  id?: Prisma.IntFilter<"bookings"> | number
  resource_id?: Prisma.IntFilter<"bookings"> | number
  customer_name?: Prisma.StringFilter<"bookings"> | string
  customer_phone?: Prisma.StringNullableFilter<"bookings"> | string | null
  customer_email?: Prisma.StringNullableFilter<"bookings"> | string | null
  start_time?: Prisma.DateTimeFilter<"bookings"> | Date | string
  end_time?: Prisma.DateTimeFilter<"bookings"> | Date | string
  status?: Prisma.Enumbooking_statusFilter<"bookings"> | $Enums.booking_status
  service_id?: Prisma.IntNullableFilter<"bookings"> | number | null
  created_at?: Prisma.DateTimeFilter<"bookings"> | Date | string
  resources?: Prisma.XOR<Prisma.ResourcesScalarRelationFilter, Prisma.resourcesWhereInput>
  salon_services?: Prisma.XOR<Prisma.Salon_servicesNullableScalarRelationFilter, Prisma.salon_servicesWhereInput> | null
}

export type bookingsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  customer_name?: Prisma.SortOrder
  customer_phone?: Prisma.SortOrderInput | Prisma.SortOrder
  customer_email?: Prisma.SortOrderInput | Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  status?: Prisma.SortOrder
  service_id?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  resources?: Prisma.resourcesOrderByWithRelationInput
  salon_services?: Prisma.salon_servicesOrderByWithRelationInput
}

export type bookingsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.bookingsWhereInput | Prisma.bookingsWhereInput[]
  OR?: Prisma.bookingsWhereInput[]
  NOT?: Prisma.bookingsWhereInput | Prisma.bookingsWhereInput[]
  resource_id?: Prisma.IntFilter<"bookings"> | number
  customer_name?: Prisma.StringFilter<"bookings"> | string
  customer_phone?: Prisma.StringNullableFilter<"bookings"> | string | null
  customer_email?: Prisma.StringNullableFilter<"bookings"> | string | null
  start_time?: Prisma.DateTimeFilter<"bookings"> | Date | string
  end_time?: Prisma.DateTimeFilter<"bookings"> | Date | string
  status?: Prisma.Enumbooking_statusFilter<"bookings"> | $Enums.booking_status
  service_id?: Prisma.IntNullableFilter<"bookings"> | number | null
  created_at?: Prisma.DateTimeFilter<"bookings"> | Date | string
  resources?: Prisma.XOR<Prisma.ResourcesScalarRelationFilter, Prisma.resourcesWhereInput>
  salon_services?: Prisma.XOR<Prisma.Salon_servicesNullableScalarRelationFilter, Prisma.salon_servicesWhereInput> | null
}, "id">

export type bookingsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  customer_name?: Prisma.SortOrder
  customer_phone?: Prisma.SortOrderInput | Prisma.SortOrder
  customer_email?: Prisma.SortOrderInput | Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  status?: Prisma.SortOrder
  service_id?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.bookingsCountOrderByAggregateInput
  _avg?: Prisma.bookingsAvgOrderByAggregateInput
  _max?: Prisma.bookingsMaxOrderByAggregateInput
  _min?: Prisma.bookingsMinOrderByAggregateInput
  _sum?: Prisma.bookingsSumOrderByAggregateInput
}

export type bookingsScalarWhereWithAggregatesInput = {
  AND?: Prisma.bookingsScalarWhereWithAggregatesInput | Prisma.bookingsScalarWhereWithAggregatesInput[]
  OR?: Prisma.bookingsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.bookingsScalarWhereWithAggregatesInput | Prisma.bookingsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"bookings"> | number
  resource_id?: Prisma.IntWithAggregatesFilter<"bookings"> | number
  customer_name?: Prisma.StringWithAggregatesFilter<"bookings"> | string
  customer_phone?: Prisma.StringNullableWithAggregatesFilter<"bookings"> | string | null
  customer_email?: Prisma.StringNullableWithAggregatesFilter<"bookings"> | string | null
  start_time?: Prisma.DateTimeWithAggregatesFilter<"bookings"> | Date | string
  end_time?: Prisma.DateTimeWithAggregatesFilter<"bookings"> | Date | string
  status?: Prisma.Enumbooking_statusWithAggregatesFilter<"bookings"> | $Enums.booking_status
  service_id?: Prisma.IntNullableWithAggregatesFilter<"bookings"> | number | null
  created_at?: Prisma.DateTimeWithAggregatesFilter<"bookings"> | Date | string
}

export type bookingsCreateInput = {
  customer_name: string
  customer_phone?: string | null
  customer_email?: string | null
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.booking_status
  created_at?: Date | string
  resources: Prisma.resourcesCreateNestedOneWithoutBookingsInput
  salon_services?: Prisma.salon_servicesCreateNestedOneWithoutBookingsInput
}

export type bookingsUncheckedCreateInput = {
  id?: number
  resource_id: number
  customer_name: string
  customer_phone?: string | null
  customer_email?: string | null
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.booking_status
  service_id?: number | null
  created_at?: Date | string
}

export type bookingsUpdateInput = {
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  customer_phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.Enumbooking_statusFieldUpdateOperationsInput | $Enums.booking_status
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resources?: Prisma.resourcesUpdateOneRequiredWithoutBookingsNestedInput
  salon_services?: Prisma.salon_servicesUpdateOneWithoutBookingsNestedInput
}

export type bookingsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resource_id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  customer_phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.Enumbooking_statusFieldUpdateOperationsInput | $Enums.booking_status
  service_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type bookingsCreateManyInput = {
  id?: number
  resource_id: number
  customer_name: string
  customer_phone?: string | null
  customer_email?: string | null
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.booking_status
  service_id?: number | null
  created_at?: Date | string
}

export type bookingsUpdateManyMutationInput = {
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  customer_phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.Enumbooking_statusFieldUpdateOperationsInput | $Enums.booking_status
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type bookingsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resource_id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  customer_phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.Enumbooking_statusFieldUpdateOperationsInput | $Enums.booking_status
  service_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type bookingsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  customer_name?: Prisma.SortOrder
  customer_phone?: Prisma.SortOrder
  customer_email?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  status?: Prisma.SortOrder
  service_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type bookingsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  service_id?: Prisma.SortOrder
}

export type bookingsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  customer_name?: Prisma.SortOrder
  customer_phone?: Prisma.SortOrder
  customer_email?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  status?: Prisma.SortOrder
  service_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type bookingsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  customer_name?: Prisma.SortOrder
  customer_phone?: Prisma.SortOrder
  customer_email?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  status?: Prisma.SortOrder
  service_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type bookingsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  service_id?: Prisma.SortOrder
}

export type BookingsListRelationFilter = {
  every?: Prisma.bookingsWhereInput
  some?: Prisma.bookingsWhereInput
  none?: Prisma.bookingsWhereInput
}

export type bookingsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type Enumbooking_statusFieldUpdateOperationsInput = {
  set?: $Enums.booking_status
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type bookingsCreateNestedManyWithoutResourcesInput = {
  create?: Prisma.XOR<Prisma.bookingsCreateWithoutResourcesInput, Prisma.bookingsUncheckedCreateWithoutResourcesInput> | Prisma.bookingsCreateWithoutResourcesInput[] | Prisma.bookingsUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.bookingsCreateOrConnectWithoutResourcesInput | Prisma.bookingsCreateOrConnectWithoutResourcesInput[]
  createMany?: Prisma.bookingsCreateManyResourcesInputEnvelope
  connect?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
}

export type bookingsUncheckedCreateNestedManyWithoutResourcesInput = {
  create?: Prisma.XOR<Prisma.bookingsCreateWithoutResourcesInput, Prisma.bookingsUncheckedCreateWithoutResourcesInput> | Prisma.bookingsCreateWithoutResourcesInput[] | Prisma.bookingsUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.bookingsCreateOrConnectWithoutResourcesInput | Prisma.bookingsCreateOrConnectWithoutResourcesInput[]
  createMany?: Prisma.bookingsCreateManyResourcesInputEnvelope
  connect?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
}

export type bookingsUpdateManyWithoutResourcesNestedInput = {
  create?: Prisma.XOR<Prisma.bookingsCreateWithoutResourcesInput, Prisma.bookingsUncheckedCreateWithoutResourcesInput> | Prisma.bookingsCreateWithoutResourcesInput[] | Prisma.bookingsUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.bookingsCreateOrConnectWithoutResourcesInput | Prisma.bookingsCreateOrConnectWithoutResourcesInput[]
  upsert?: Prisma.bookingsUpsertWithWhereUniqueWithoutResourcesInput | Prisma.bookingsUpsertWithWhereUniqueWithoutResourcesInput[]
  createMany?: Prisma.bookingsCreateManyResourcesInputEnvelope
  set?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  disconnect?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  delete?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  connect?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  update?: Prisma.bookingsUpdateWithWhereUniqueWithoutResourcesInput | Prisma.bookingsUpdateWithWhereUniqueWithoutResourcesInput[]
  updateMany?: Prisma.bookingsUpdateManyWithWhereWithoutResourcesInput | Prisma.bookingsUpdateManyWithWhereWithoutResourcesInput[]
  deleteMany?: Prisma.bookingsScalarWhereInput | Prisma.bookingsScalarWhereInput[]
}

export type bookingsUncheckedUpdateManyWithoutResourcesNestedInput = {
  create?: Prisma.XOR<Prisma.bookingsCreateWithoutResourcesInput, Prisma.bookingsUncheckedCreateWithoutResourcesInput> | Prisma.bookingsCreateWithoutResourcesInput[] | Prisma.bookingsUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.bookingsCreateOrConnectWithoutResourcesInput | Prisma.bookingsCreateOrConnectWithoutResourcesInput[]
  upsert?: Prisma.bookingsUpsertWithWhereUniqueWithoutResourcesInput | Prisma.bookingsUpsertWithWhereUniqueWithoutResourcesInput[]
  createMany?: Prisma.bookingsCreateManyResourcesInputEnvelope
  set?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  disconnect?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  delete?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  connect?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  update?: Prisma.bookingsUpdateWithWhereUniqueWithoutResourcesInput | Prisma.bookingsUpdateWithWhereUniqueWithoutResourcesInput[]
  updateMany?: Prisma.bookingsUpdateManyWithWhereWithoutResourcesInput | Prisma.bookingsUpdateManyWithWhereWithoutResourcesInput[]
  deleteMany?: Prisma.bookingsScalarWhereInput | Prisma.bookingsScalarWhereInput[]
}

export type bookingsUpdateManyWithoutSalon_servicesNestedInput = {
  create?: Prisma.XOR<Prisma.bookingsCreateWithoutSalon_servicesInput, Prisma.bookingsUncheckedCreateWithoutSalon_servicesInput> | Prisma.bookingsCreateWithoutSalon_servicesInput[] | Prisma.bookingsUncheckedCreateWithoutSalon_servicesInput[]
  connectOrCreate?: Prisma.bookingsCreateOrConnectWithoutSalon_servicesInput | Prisma.bookingsCreateOrConnectWithoutSalon_servicesInput[]
  upsert?: Prisma.bookingsUpsertWithWhereUniqueWithoutSalon_servicesInput | Prisma.bookingsUpsertWithWhereUniqueWithoutSalon_servicesInput[]
  createMany?: Prisma.bookingsCreateManySalon_servicesInputEnvelope
  set?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  disconnect?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  delete?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  connect?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  update?: Prisma.bookingsUpdateWithWhereUniqueWithoutSalon_servicesInput | Prisma.bookingsUpdateWithWhereUniqueWithoutSalon_servicesInput[]
  updateMany?: Prisma.bookingsUpdateManyWithWhereWithoutSalon_servicesInput | Prisma.bookingsUpdateManyWithWhereWithoutSalon_servicesInput[]
  deleteMany?: Prisma.bookingsScalarWhereInput | Prisma.bookingsScalarWhereInput[]
}

export type bookingsUncheckedUpdateManyWithoutSalon_servicesNestedInput = {
  create?: Prisma.XOR<Prisma.bookingsCreateWithoutSalon_servicesInput, Prisma.bookingsUncheckedCreateWithoutSalon_servicesInput> | Prisma.bookingsCreateWithoutSalon_servicesInput[] | Prisma.bookingsUncheckedCreateWithoutSalon_servicesInput[]
  connectOrCreate?: Prisma.bookingsCreateOrConnectWithoutSalon_servicesInput | Prisma.bookingsCreateOrConnectWithoutSalon_servicesInput[]
  upsert?: Prisma.bookingsUpsertWithWhereUniqueWithoutSalon_servicesInput | Prisma.bookingsUpsertWithWhereUniqueWithoutSalon_servicesInput[]
  createMany?: Prisma.bookingsCreateManySalon_servicesInputEnvelope
  set?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  disconnect?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  delete?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  connect?: Prisma.bookingsWhereUniqueInput | Prisma.bookingsWhereUniqueInput[]
  update?: Prisma.bookingsUpdateWithWhereUniqueWithoutSalon_servicesInput | Prisma.bookingsUpdateWithWhereUniqueWithoutSalon_servicesInput[]
  updateMany?: Prisma.bookingsUpdateManyWithWhereWithoutSalon_servicesInput | Prisma.bookingsUpdateManyWithWhereWithoutSalon_servicesInput[]
  deleteMany?: Prisma.bookingsScalarWhereInput | Prisma.bookingsScalarWhereInput[]
}

export type bookingsCreateWithoutResourcesInput = {
  customer_name: string
  customer_phone?: string | null
  customer_email?: string | null
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.booking_status
  created_at?: Date | string
  salon_services?: Prisma.salon_servicesCreateNestedOneWithoutBookingsInput
}

export type bookingsUncheckedCreateWithoutResourcesInput = {
  id?: number
  customer_name: string
  customer_phone?: string | null
  customer_email?: string | null
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.booking_status
  service_id?: number | null
  created_at?: Date | string
}

export type bookingsCreateOrConnectWithoutResourcesInput = {
  where: Prisma.bookingsWhereUniqueInput
  create: Prisma.XOR<Prisma.bookingsCreateWithoutResourcesInput, Prisma.bookingsUncheckedCreateWithoutResourcesInput>
}

export type bookingsCreateManyResourcesInputEnvelope = {
  data: Prisma.bookingsCreateManyResourcesInput | Prisma.bookingsCreateManyResourcesInput[]
  skipDuplicates?: boolean
}

export type bookingsUpsertWithWhereUniqueWithoutResourcesInput = {
  where: Prisma.bookingsWhereUniqueInput
  update: Prisma.XOR<Prisma.bookingsUpdateWithoutResourcesInput, Prisma.bookingsUncheckedUpdateWithoutResourcesInput>
  create: Prisma.XOR<Prisma.bookingsCreateWithoutResourcesInput, Prisma.bookingsUncheckedCreateWithoutResourcesInput>
}

export type bookingsUpdateWithWhereUniqueWithoutResourcesInput = {
  where: Prisma.bookingsWhereUniqueInput
  data: Prisma.XOR<Prisma.bookingsUpdateWithoutResourcesInput, Prisma.bookingsUncheckedUpdateWithoutResourcesInput>
}

export type bookingsUpdateManyWithWhereWithoutResourcesInput = {
  where: Prisma.bookingsScalarWhereInput
  data: Prisma.XOR<Prisma.bookingsUpdateManyMutationInput, Prisma.bookingsUncheckedUpdateManyWithoutResourcesInput>
}

export type bookingsScalarWhereInput = {
  AND?: Prisma.bookingsScalarWhereInput | Prisma.bookingsScalarWhereInput[]
  OR?: Prisma.bookingsScalarWhereInput[]
  NOT?: Prisma.bookingsScalarWhereInput | Prisma.bookingsScalarWhereInput[]
  id?: Prisma.IntFilter<"bookings"> | number
  resource_id?: Prisma.IntFilter<"bookings"> | number
  customer_name?: Prisma.StringFilter<"bookings"> | string
  customer_phone?: Prisma.StringNullableFilter<"bookings"> | string | null
  customer_email?: Prisma.StringNullableFilter<"bookings"> | string | null
  start_time?: Prisma.DateTimeFilter<"bookings"> | Date | string
  end_time?: Prisma.DateTimeFilter<"bookings"> | Date | string
  status?: Prisma.Enumbooking_statusFilter<"bookings"> | $Enums.booking_status
  service_id?: Prisma.IntNullableFilter<"bookings"> | number | null
  created_at?: Prisma.DateTimeFilter<"bookings"> | Date | string
}

export type bookingsCreateWithoutSalon_servicesInput = {
  customer_name: string
  customer_phone?: string | null
  customer_email?: string | null
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.booking_status
  created_at?: Date | string
  resources: Prisma.resourcesCreateNestedOneWithoutBookingsInput
}

export type bookingsUncheckedCreateWithoutSalon_servicesInput = {
  id?: number
  resource_id: number
  customer_name: string
  customer_phone?: string | null
  customer_email?: string | null
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.booking_status
  created_at?: Date | string
}

export type bookingsCreateOrConnectWithoutSalon_servicesInput = {
  where: Prisma.bookingsWhereUniqueInput
  create: Prisma.XOR<Prisma.bookingsCreateWithoutSalon_servicesInput, Prisma.bookingsUncheckedCreateWithoutSalon_servicesInput>
}

export type bookingsUpsertWithWhereUniqueWithoutSalon_servicesInput = {
  where: Prisma.bookingsWhereUniqueInput
  update: Prisma.XOR<Prisma.bookingsUpdateWithoutSalon_servicesInput, Prisma.bookingsUncheckedUpdateWithoutSalon_servicesInput>
  create: Prisma.XOR<Prisma.bookingsCreateWithoutSalon_servicesInput, Prisma.bookingsUncheckedCreateWithoutSalon_servicesInput>
}

export type bookingsCreateManySalon_servicesInputEnvelope = {
  data: Prisma.bookingsCreateManySalon_servicesInput | Prisma.bookingsCreateManySalon_servicesInput[]
  skipDuplicates?: boolean
}

export type bookingsUpdateWithWhereUniqueWithoutSalon_servicesInput = {
  where: Prisma.bookingsWhereUniqueInput
  data: Prisma.XOR<Prisma.bookingsUpdateWithoutSalon_servicesInput, Prisma.bookingsUncheckedUpdateWithoutSalon_servicesInput>
}

export type bookingsUpdateManyWithWhereWithoutSalon_servicesInput = {
  where: Prisma.bookingsScalarWhereInput
  data: Prisma.XOR<Prisma.bookingsUpdateManyMutationInput, Prisma.bookingsUncheckedUpdateManyWithoutSalon_servicesInput>
}

export type bookingsCreateManyResourcesInput = {
  id?: number
  customer_name: string
  customer_phone?: string | null
  customer_email?: string | null
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.booking_status
  service_id?: number | null
  created_at?: Date | string
}

export type bookingsUpdateWithoutResourcesInput = {
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  customer_phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.Enumbooking_statusFieldUpdateOperationsInput | $Enums.booking_status
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  salon_services?: Prisma.salon_servicesUpdateOneWithoutBookingsNestedInput
}

export type bookingsUncheckedUpdateWithoutResourcesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  customer_phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.Enumbooking_statusFieldUpdateOperationsInput | $Enums.booking_status
  service_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type bookingsUncheckedUpdateManyWithoutResourcesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  customer_phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.Enumbooking_statusFieldUpdateOperationsInput | $Enums.booking_status
  service_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type bookingsUpdateWithoutSalon_servicesInput = {
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  customer_phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.Enumbooking_statusFieldUpdateOperationsInput | $Enums.booking_status
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resources?: Prisma.resourcesUpdateOneRequiredWithoutBookingsNestedInput
}

export type bookingsUncheckedUpdateWithoutSalon_servicesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resource_id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  customer_phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.Enumbooking_statusFieldUpdateOperationsInput | $Enums.booking_status
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type bookingsCreateManySalon_servicesInput = {
  id?: number
  resource_id: number
  customer_name: string
  customer_phone?: string | null
  customer_email?: string | null
  start_time: Date | string
  end_time: Date | string
  status?: $Enums.booking_status
  created_at?: Date | string
}

export type bookingsUncheckedUpdateManyWithoutSalon_servicesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resource_id?: Prisma.IntFieldUpdateOperationsInput | number
  customer_name?: Prisma.StringFieldUpdateOperationsInput | string
  customer_phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customer_email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.Enumbooking_statusFieldUpdateOperationsInput | $Enums.booking_status
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type bookingsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  resource_id?: boolean
  customer_name?: boolean
  customer_phone?: boolean
  customer_email?: boolean
  start_time?: boolean
  end_time?: boolean
  status?: boolean
  service_id?: boolean
  created_at?: boolean
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
  salon_services?: boolean | Prisma.bookings$salon_servicesArgs<ExtArgs>
}, ExtArgs["result"]["bookings"]>

export type bookingsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  resource_id?: boolean
  customer_name?: boolean
  customer_phone?: boolean
  customer_email?: boolean
  start_time?: boolean
  end_time?: boolean
  status?: boolean
  service_id?: boolean
  created_at?: boolean
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
  salon_services?: boolean | Prisma.bookings$salon_servicesArgs<ExtArgs>
}, ExtArgs["result"]["bookings"]>

export type bookingsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  resource_id?: boolean
  customer_name?: boolean
  customer_phone?: boolean
  customer_email?: boolean
  start_time?: boolean
  end_time?: boolean
  status?: boolean
  service_id?: boolean
  created_at?: boolean
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
  salon_services?: boolean | Prisma.bookings$salon_servicesArgs<ExtArgs>
}, ExtArgs["result"]["bookings"]>

export type bookingsSelectScalar = {
  id?: boolean
  resource_id?: boolean
  customer_name?: boolean
  customer_phone?: boolean
  customer_email?: boolean
  start_time?: boolean
  end_time?: boolean
  status?: boolean
  service_id?: boolean
  created_at?: boolean
}

export type bookingsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "resource_id" | "customer_name" | "customer_phone" | "customer_email" | "start_time" | "end_time" | "status" | "service_id" | "created_at", ExtArgs["result"]["bookings"]>
export type bookingsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
  salon_services?: boolean | Prisma.bookings$salon_servicesArgs<ExtArgs>
}
export type bookingsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
  salon_services?: boolean | Prisma.bookings$salon_servicesArgs<ExtArgs>
}
export type bookingsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
  salon_services?: boolean | Prisma.bookings$salon_servicesArgs<ExtArgs>
}

export type $bookingsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "bookings"
  objects: {
    resources: Prisma.$resourcesPayload<ExtArgs>
    salon_services: Prisma.$salon_servicesPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    resource_id: number
    customer_name: string
    customer_phone: string | null
    customer_email: string | null
    start_time: Date
    end_time: Date
    status: $Enums.booking_status
    service_id: number | null
    created_at: Date
  }, ExtArgs["result"]["bookings"]>
  composites: {}
}

export type bookingsGetPayload<S extends boolean | null | undefined | bookingsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$bookingsPayload, S>

export type bookingsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<bookingsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BookingsCountAggregateInputType | true
  }

export interface bookingsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['bookings'], meta: { name: 'bookings' } }
  /**
   * Find zero or one Bookings that matches the filter.
   * @param {bookingsFindUniqueArgs} args - Arguments to find a Bookings
   * @example
   * // Get one Bookings
   * const bookings = await prisma.bookings.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends bookingsFindUniqueArgs>(args: Prisma.SelectSubset<T, bookingsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__bookingsClient<runtime.Types.Result.GetResult<Prisma.$bookingsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Bookings that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {bookingsFindUniqueOrThrowArgs} args - Arguments to find a Bookings
   * @example
   * // Get one Bookings
   * const bookings = await prisma.bookings.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends bookingsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, bookingsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__bookingsClient<runtime.Types.Result.GetResult<Prisma.$bookingsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Bookings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {bookingsFindFirstArgs} args - Arguments to find a Bookings
   * @example
   * // Get one Bookings
   * const bookings = await prisma.bookings.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends bookingsFindFirstArgs>(args?: Prisma.SelectSubset<T, bookingsFindFirstArgs<ExtArgs>>): Prisma.Prisma__bookingsClient<runtime.Types.Result.GetResult<Prisma.$bookingsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Bookings that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {bookingsFindFirstOrThrowArgs} args - Arguments to find a Bookings
   * @example
   * // Get one Bookings
   * const bookings = await prisma.bookings.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends bookingsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, bookingsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__bookingsClient<runtime.Types.Result.GetResult<Prisma.$bookingsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Bookings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {bookingsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Bookings
   * const bookings = await prisma.bookings.findMany()
   * 
   * // Get first 10 Bookings
   * const bookings = await prisma.bookings.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const bookingsWithIdOnly = await prisma.bookings.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends bookingsFindManyArgs>(args?: Prisma.SelectSubset<T, bookingsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$bookingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Bookings.
   * @param {bookingsCreateArgs} args - Arguments to create a Bookings.
   * @example
   * // Create one Bookings
   * const Bookings = await prisma.bookings.create({
   *   data: {
   *     // ... data to create a Bookings
   *   }
   * })
   * 
   */
  create<T extends bookingsCreateArgs>(args: Prisma.SelectSubset<T, bookingsCreateArgs<ExtArgs>>): Prisma.Prisma__bookingsClient<runtime.Types.Result.GetResult<Prisma.$bookingsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Bookings.
   * @param {bookingsCreateManyArgs} args - Arguments to create many Bookings.
   * @example
   * // Create many Bookings
   * const bookings = await prisma.bookings.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends bookingsCreateManyArgs>(args?: Prisma.SelectSubset<T, bookingsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Bookings and returns the data saved in the database.
   * @param {bookingsCreateManyAndReturnArgs} args - Arguments to create many Bookings.
   * @example
   * // Create many Bookings
   * const bookings = await prisma.bookings.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Bookings and only return the `id`
   * const bookingsWithIdOnly = await prisma.bookings.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends bookingsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, bookingsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$bookingsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Bookings.
   * @param {bookingsDeleteArgs} args - Arguments to delete one Bookings.
   * @example
   * // Delete one Bookings
   * const Bookings = await prisma.bookings.delete({
   *   where: {
   *     // ... filter to delete one Bookings
   *   }
   * })
   * 
   */
  delete<T extends bookingsDeleteArgs>(args: Prisma.SelectSubset<T, bookingsDeleteArgs<ExtArgs>>): Prisma.Prisma__bookingsClient<runtime.Types.Result.GetResult<Prisma.$bookingsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Bookings.
   * @param {bookingsUpdateArgs} args - Arguments to update one Bookings.
   * @example
   * // Update one Bookings
   * const bookings = await prisma.bookings.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends bookingsUpdateArgs>(args: Prisma.SelectSubset<T, bookingsUpdateArgs<ExtArgs>>): Prisma.Prisma__bookingsClient<runtime.Types.Result.GetResult<Prisma.$bookingsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Bookings.
   * @param {bookingsDeleteManyArgs} args - Arguments to filter Bookings to delete.
   * @example
   * // Delete a few Bookings
   * const { count } = await prisma.bookings.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends bookingsDeleteManyArgs>(args?: Prisma.SelectSubset<T, bookingsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Bookings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {bookingsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Bookings
   * const bookings = await prisma.bookings.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends bookingsUpdateManyArgs>(args: Prisma.SelectSubset<T, bookingsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Bookings and returns the data updated in the database.
   * @param {bookingsUpdateManyAndReturnArgs} args - Arguments to update many Bookings.
   * @example
   * // Update many Bookings
   * const bookings = await prisma.bookings.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Bookings and only return the `id`
   * const bookingsWithIdOnly = await prisma.bookings.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends bookingsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, bookingsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$bookingsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Bookings.
   * @param {bookingsUpsertArgs} args - Arguments to update or create a Bookings.
   * @example
   * // Update or create a Bookings
   * const bookings = await prisma.bookings.upsert({
   *   create: {
   *     // ... data to create a Bookings
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Bookings we want to update
   *   }
   * })
   */
  upsert<T extends bookingsUpsertArgs>(args: Prisma.SelectSubset<T, bookingsUpsertArgs<ExtArgs>>): Prisma.Prisma__bookingsClient<runtime.Types.Result.GetResult<Prisma.$bookingsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Bookings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {bookingsCountArgs} args - Arguments to filter Bookings to count.
   * @example
   * // Count the number of Bookings
   * const count = await prisma.bookings.count({
   *   where: {
   *     // ... the filter for the Bookings we want to count
   *   }
   * })
  **/
  count<T extends bookingsCountArgs>(
    args?: Prisma.Subset<T, bookingsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BookingsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Bookings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BookingsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BookingsAggregateArgs>(args: Prisma.Subset<T, BookingsAggregateArgs>): Prisma.PrismaPromise<GetBookingsAggregateType<T>>

  /**
   * Group by Bookings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {bookingsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends bookingsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: bookingsGroupByArgs['orderBy'] }
      : { orderBy?: bookingsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, bookingsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBookingsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the bookings model
 */
readonly fields: bookingsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for bookings.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__bookingsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  resources<T extends Prisma.resourcesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.resourcesDefaultArgs<ExtArgs>>): Prisma.Prisma__resourcesClient<runtime.Types.Result.GetResult<Prisma.$resourcesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  salon_services<T extends Prisma.bookings$salon_servicesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.bookings$salon_servicesArgs<ExtArgs>>): Prisma.Prisma__salon_servicesClient<runtime.Types.Result.GetResult<Prisma.$salon_servicesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the bookings model
 */
export interface bookingsFieldRefs {
  readonly id: Prisma.FieldRef<"bookings", 'Int'>
  readonly resource_id: Prisma.FieldRef<"bookings", 'Int'>
  readonly customer_name: Prisma.FieldRef<"bookings", 'String'>
  readonly customer_phone: Prisma.FieldRef<"bookings", 'String'>
  readonly customer_email: Prisma.FieldRef<"bookings", 'String'>
  readonly start_time: Prisma.FieldRef<"bookings", 'DateTime'>
  readonly end_time: Prisma.FieldRef<"bookings", 'DateTime'>
  readonly status: Prisma.FieldRef<"bookings", 'booking_status'>
  readonly service_id: Prisma.FieldRef<"bookings", 'Int'>
  readonly created_at: Prisma.FieldRef<"bookings", 'DateTime'>
}
    

// Custom InputTypes
/**
 * bookings findUnique
 */
export type bookingsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bookings
   */
  select?: Prisma.bookingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the bookings
   */
  omit?: Prisma.bookingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bookingsInclude<ExtArgs> | null
  /**
   * Filter, which bookings to fetch.
   */
  where: Prisma.bookingsWhereUniqueInput
}

/**
 * bookings findUniqueOrThrow
 */
export type bookingsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bookings
   */
  select?: Prisma.bookingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the bookings
   */
  omit?: Prisma.bookingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bookingsInclude<ExtArgs> | null
  /**
   * Filter, which bookings to fetch.
   */
  where: Prisma.bookingsWhereUniqueInput
}

/**
 * bookings findFirst
 */
export type bookingsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bookings
   */
  select?: Prisma.bookingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the bookings
   */
  omit?: Prisma.bookingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bookingsInclude<ExtArgs> | null
  /**
   * Filter, which bookings to fetch.
   */
  where?: Prisma.bookingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of bookings to fetch.
   */
  orderBy?: Prisma.bookingsOrderByWithRelationInput | Prisma.bookingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for bookings.
   */
  cursor?: Prisma.bookingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` bookings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` bookings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of bookings.
   */
  distinct?: Prisma.BookingsScalarFieldEnum | Prisma.BookingsScalarFieldEnum[]
}

/**
 * bookings findFirstOrThrow
 */
export type bookingsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bookings
   */
  select?: Prisma.bookingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the bookings
   */
  omit?: Prisma.bookingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bookingsInclude<ExtArgs> | null
  /**
   * Filter, which bookings to fetch.
   */
  where?: Prisma.bookingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of bookings to fetch.
   */
  orderBy?: Prisma.bookingsOrderByWithRelationInput | Prisma.bookingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for bookings.
   */
  cursor?: Prisma.bookingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` bookings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` bookings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of bookings.
   */
  distinct?: Prisma.BookingsScalarFieldEnum | Prisma.BookingsScalarFieldEnum[]
}

/**
 * bookings findMany
 */
export type bookingsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bookings
   */
  select?: Prisma.bookingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the bookings
   */
  omit?: Prisma.bookingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bookingsInclude<ExtArgs> | null
  /**
   * Filter, which bookings to fetch.
   */
  where?: Prisma.bookingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of bookings to fetch.
   */
  orderBy?: Prisma.bookingsOrderByWithRelationInput | Prisma.bookingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing bookings.
   */
  cursor?: Prisma.bookingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` bookings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` bookings.
   */
  skip?: number
  distinct?: Prisma.BookingsScalarFieldEnum | Prisma.BookingsScalarFieldEnum[]
}

/**
 * bookings create
 */
export type bookingsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bookings
   */
  select?: Prisma.bookingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the bookings
   */
  omit?: Prisma.bookingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bookingsInclude<ExtArgs> | null
  /**
   * The data needed to create a bookings.
   */
  data: Prisma.XOR<Prisma.bookingsCreateInput, Prisma.bookingsUncheckedCreateInput>
}

/**
 * bookings createMany
 */
export type bookingsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many bookings.
   */
  data: Prisma.bookingsCreateManyInput | Prisma.bookingsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * bookings createManyAndReturn
 */
export type bookingsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bookings
   */
  select?: Prisma.bookingsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the bookings
   */
  omit?: Prisma.bookingsOmit<ExtArgs> | null
  /**
   * The data used to create many bookings.
   */
  data: Prisma.bookingsCreateManyInput | Prisma.bookingsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bookingsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * bookings update
 */
export type bookingsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bookings
   */
  select?: Prisma.bookingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the bookings
   */
  omit?: Prisma.bookingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bookingsInclude<ExtArgs> | null
  /**
   * The data needed to update a bookings.
   */
  data: Prisma.XOR<Prisma.bookingsUpdateInput, Prisma.bookingsUncheckedUpdateInput>
  /**
   * Choose, which bookings to update.
   */
  where: Prisma.bookingsWhereUniqueInput
}

/**
 * bookings updateMany
 */
export type bookingsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update bookings.
   */
  data: Prisma.XOR<Prisma.bookingsUpdateManyMutationInput, Prisma.bookingsUncheckedUpdateManyInput>
  /**
   * Filter which bookings to update
   */
  where?: Prisma.bookingsWhereInput
  /**
   * Limit how many bookings to update.
   */
  limit?: number
}

/**
 * bookings updateManyAndReturn
 */
export type bookingsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bookings
   */
  select?: Prisma.bookingsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the bookings
   */
  omit?: Prisma.bookingsOmit<ExtArgs> | null
  /**
   * The data used to update bookings.
   */
  data: Prisma.XOR<Prisma.bookingsUpdateManyMutationInput, Prisma.bookingsUncheckedUpdateManyInput>
  /**
   * Filter which bookings to update
   */
  where?: Prisma.bookingsWhereInput
  /**
   * Limit how many bookings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bookingsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * bookings upsert
 */
export type bookingsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bookings
   */
  select?: Prisma.bookingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the bookings
   */
  omit?: Prisma.bookingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bookingsInclude<ExtArgs> | null
  /**
   * The filter to search for the bookings to update in case it exists.
   */
  where: Prisma.bookingsWhereUniqueInput
  /**
   * In case the bookings found by the `where` argument doesn't exist, create a new bookings with this data.
   */
  create: Prisma.XOR<Prisma.bookingsCreateInput, Prisma.bookingsUncheckedCreateInput>
  /**
   * In case the bookings was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.bookingsUpdateInput, Prisma.bookingsUncheckedUpdateInput>
}

/**
 * bookings delete
 */
export type bookingsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bookings
   */
  select?: Prisma.bookingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the bookings
   */
  omit?: Prisma.bookingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bookingsInclude<ExtArgs> | null
  /**
   * Filter which bookings to delete.
   */
  where: Prisma.bookingsWhereUniqueInput
}

/**
 * bookings deleteMany
 */
export type bookingsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which bookings to delete
   */
  where?: Prisma.bookingsWhereInput
  /**
   * Limit how many bookings to delete.
   */
  limit?: number
}

/**
 * bookings.salon_services
 */
export type bookings$salon_servicesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the salon_services
   */
  select?: Prisma.salon_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the salon_services
   */
  omit?: Prisma.salon_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.salon_servicesInclude<ExtArgs> | null
  where?: Prisma.salon_servicesWhereInput
}

/**
 * bookings without action
 */
export type bookingsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bookings
   */
  select?: Prisma.bookingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the bookings
   */
  omit?: Prisma.bookingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bookingsInclude<ExtArgs> | null
}
