
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `resource_services` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model resource_services
 * 
 */
export type resource_servicesModel = runtime.Types.Result.DefaultSelection<Prisma.$resource_servicesPayload>

export type AggregateResource_services = {
  _count: Resource_servicesCountAggregateOutputType | null
  _avg: Resource_servicesAvgAggregateOutputType | null
  _sum: Resource_servicesSumAggregateOutputType | null
  _min: Resource_servicesMinAggregateOutputType | null
  _max: Resource_servicesMaxAggregateOutputType | null
}

export type Resource_servicesAvgAggregateOutputType = {
  resource_id: number | null
  service_id: number | null
}

export type Resource_servicesSumAggregateOutputType = {
  resource_id: number | null
  service_id: number | null
}

export type Resource_servicesMinAggregateOutputType = {
  resource_id: number | null
  service_id: number | null
}

export type Resource_servicesMaxAggregateOutputType = {
  resource_id: number | null
  service_id: number | null
}

export type Resource_servicesCountAggregateOutputType = {
  resource_id: number
  service_id: number
  _all: number
}


export type Resource_servicesAvgAggregateInputType = {
  resource_id?: true
  service_id?: true
}

export type Resource_servicesSumAggregateInputType = {
  resource_id?: true
  service_id?: true
}

export type Resource_servicesMinAggregateInputType = {
  resource_id?: true
  service_id?: true
}

export type Resource_servicesMaxAggregateInputType = {
  resource_id?: true
  service_id?: true
}

export type Resource_servicesCountAggregateInputType = {
  resource_id?: true
  service_id?: true
  _all?: true
}

export type Resource_servicesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which resource_services to aggregate.
   */
  where?: Prisma.resource_servicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of resource_services to fetch.
   */
  orderBy?: Prisma.resource_servicesOrderByWithRelationInput | Prisma.resource_servicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.resource_servicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` resource_services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` resource_services.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned resource_services
  **/
  _count?: true | Resource_servicesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Resource_servicesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Resource_servicesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Resource_servicesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Resource_servicesMaxAggregateInputType
}

export type GetResource_servicesAggregateType<T extends Resource_servicesAggregateArgs> = {
      [P in keyof T & keyof AggregateResource_services]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateResource_services[P]>
    : Prisma.GetScalarType<T[P], AggregateResource_services[P]>
}




export type resource_servicesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.resource_servicesWhereInput
  orderBy?: Prisma.resource_servicesOrderByWithAggregationInput | Prisma.resource_servicesOrderByWithAggregationInput[]
  by: Prisma.Resource_servicesScalarFieldEnum[] | Prisma.Resource_servicesScalarFieldEnum
  having?: Prisma.resource_servicesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Resource_servicesCountAggregateInputType | true
  _avg?: Resource_servicesAvgAggregateInputType
  _sum?: Resource_servicesSumAggregateInputType
  _min?: Resource_servicesMinAggregateInputType
  _max?: Resource_servicesMaxAggregateInputType
}

export type Resource_servicesGroupByOutputType = {
  resource_id: number
  service_id: number
  _count: Resource_servicesCountAggregateOutputType | null
  _avg: Resource_servicesAvgAggregateOutputType | null
  _sum: Resource_servicesSumAggregateOutputType | null
  _min: Resource_servicesMinAggregateOutputType | null
  _max: Resource_servicesMaxAggregateOutputType | null
}

type GetResource_servicesGroupByPayload<T extends resource_servicesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Resource_servicesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Resource_servicesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Resource_servicesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Resource_servicesGroupByOutputType[P]>
      }
    >
  >



export type resource_servicesWhereInput = {
  AND?: Prisma.resource_servicesWhereInput | Prisma.resource_servicesWhereInput[]
  OR?: Prisma.resource_servicesWhereInput[]
  NOT?: Prisma.resource_servicesWhereInput | Prisma.resource_servicesWhereInput[]
  resource_id?: Prisma.IntFilter<"resource_services"> | number
  service_id?: Prisma.IntFilter<"resource_services"> | number
  resources?: Prisma.XOR<Prisma.ResourcesScalarRelationFilter, Prisma.resourcesWhereInput>
  salon_services?: Prisma.XOR<Prisma.Salon_servicesScalarRelationFilter, Prisma.salon_servicesWhereInput>
}

export type resource_servicesOrderByWithRelationInput = {
  resource_id?: Prisma.SortOrder
  service_id?: Prisma.SortOrder
  resources?: Prisma.resourcesOrderByWithRelationInput
  salon_services?: Prisma.salon_servicesOrderByWithRelationInput
}

export type resource_servicesWhereUniqueInput = Prisma.AtLeast<{
  resource_id_service_id?: Prisma.resource_servicesResource_idService_idCompoundUniqueInput
  AND?: Prisma.resource_servicesWhereInput | Prisma.resource_servicesWhereInput[]
  OR?: Prisma.resource_servicesWhereInput[]
  NOT?: Prisma.resource_servicesWhereInput | Prisma.resource_servicesWhereInput[]
  resource_id?: Prisma.IntFilter<"resource_services"> | number
  service_id?: Prisma.IntFilter<"resource_services"> | number
  resources?: Prisma.XOR<Prisma.ResourcesScalarRelationFilter, Prisma.resourcesWhereInput>
  salon_services?: Prisma.XOR<Prisma.Salon_servicesScalarRelationFilter, Prisma.salon_servicesWhereInput>
}, "resource_id_service_id">

export type resource_servicesOrderByWithAggregationInput = {
  resource_id?: Prisma.SortOrder
  service_id?: Prisma.SortOrder
  _count?: Prisma.resource_servicesCountOrderByAggregateInput
  _avg?: Prisma.resource_servicesAvgOrderByAggregateInput
  _max?: Prisma.resource_servicesMaxOrderByAggregateInput
  _min?: Prisma.resource_servicesMinOrderByAggregateInput
  _sum?: Prisma.resource_servicesSumOrderByAggregateInput
}

export type resource_servicesScalarWhereWithAggregatesInput = {
  AND?: Prisma.resource_servicesScalarWhereWithAggregatesInput | Prisma.resource_servicesScalarWhereWithAggregatesInput[]
  OR?: Prisma.resource_servicesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.resource_servicesScalarWhereWithAggregatesInput | Prisma.resource_servicesScalarWhereWithAggregatesInput[]
  resource_id?: Prisma.IntWithAggregatesFilter<"resource_services"> | number
  service_id?: Prisma.IntWithAggregatesFilter<"resource_services"> | number
}

export type resource_servicesCreateInput = {
  resources: Prisma.resourcesCreateNestedOneWithoutResource_servicesInput
  salon_services: Prisma.salon_servicesCreateNestedOneWithoutResource_servicesInput
}

export type resource_servicesUncheckedCreateInput = {
  resource_id: number
  service_id: number
}

export type resource_servicesUpdateInput = {
  resources?: Prisma.resourcesUpdateOneRequiredWithoutResource_servicesNestedInput
  salon_services?: Prisma.salon_servicesUpdateOneRequiredWithoutResource_servicesNestedInput
}

export type resource_servicesUncheckedUpdateInput = {
  resource_id?: Prisma.IntFieldUpdateOperationsInput | number
  service_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type resource_servicesCreateManyInput = {
  resource_id: number
  service_id: number
}

export type resource_servicesUpdateManyMutationInput = {

}

export type resource_servicesUncheckedUpdateManyInput = {
  resource_id?: Prisma.IntFieldUpdateOperationsInput | number
  service_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type resource_servicesResource_idService_idCompoundUniqueInput = {
  resource_id: number
  service_id: number
}

export type resource_servicesCountOrderByAggregateInput = {
  resource_id?: Prisma.SortOrder
  service_id?: Prisma.SortOrder
}

export type resource_servicesAvgOrderByAggregateInput = {
  resource_id?: Prisma.SortOrder
  service_id?: Prisma.SortOrder
}

export type resource_servicesMaxOrderByAggregateInput = {
  resource_id?: Prisma.SortOrder
  service_id?: Prisma.SortOrder
}

export type resource_servicesMinOrderByAggregateInput = {
  resource_id?: Prisma.SortOrder
  service_id?: Prisma.SortOrder
}

export type resource_servicesSumOrderByAggregateInput = {
  resource_id?: Prisma.SortOrder
  service_id?: Prisma.SortOrder
}

export type Resource_servicesListRelationFilter = {
  every?: Prisma.resource_servicesWhereInput
  some?: Prisma.resource_servicesWhereInput
  none?: Prisma.resource_servicesWhereInput
}

export type resource_servicesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type resource_servicesCreateNestedManyWithoutResourcesInput = {
  create?: Prisma.XOR<Prisma.resource_servicesCreateWithoutResourcesInput, Prisma.resource_servicesUncheckedCreateWithoutResourcesInput> | Prisma.resource_servicesCreateWithoutResourcesInput[] | Prisma.resource_servicesUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.resource_servicesCreateOrConnectWithoutResourcesInput | Prisma.resource_servicesCreateOrConnectWithoutResourcesInput[]
  createMany?: Prisma.resource_servicesCreateManyResourcesInputEnvelope
  connect?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
}

export type resource_servicesUncheckedCreateNestedManyWithoutResourcesInput = {
  create?: Prisma.XOR<Prisma.resource_servicesCreateWithoutResourcesInput, Prisma.resource_servicesUncheckedCreateWithoutResourcesInput> | Prisma.resource_servicesCreateWithoutResourcesInput[] | Prisma.resource_servicesUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.resource_servicesCreateOrConnectWithoutResourcesInput | Prisma.resource_servicesCreateOrConnectWithoutResourcesInput[]
  createMany?: Prisma.resource_servicesCreateManyResourcesInputEnvelope
  connect?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
}

export type resource_servicesUpdateManyWithoutResourcesNestedInput = {
  create?: Prisma.XOR<Prisma.resource_servicesCreateWithoutResourcesInput, Prisma.resource_servicesUncheckedCreateWithoutResourcesInput> | Prisma.resource_servicesCreateWithoutResourcesInput[] | Prisma.resource_servicesUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.resource_servicesCreateOrConnectWithoutResourcesInput | Prisma.resource_servicesCreateOrConnectWithoutResourcesInput[]
  upsert?: Prisma.resource_servicesUpsertWithWhereUniqueWithoutResourcesInput | Prisma.resource_servicesUpsertWithWhereUniqueWithoutResourcesInput[]
  createMany?: Prisma.resource_servicesCreateManyResourcesInputEnvelope
  set?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  disconnect?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  delete?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  connect?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  update?: Prisma.resource_servicesUpdateWithWhereUniqueWithoutResourcesInput | Prisma.resource_servicesUpdateWithWhereUniqueWithoutResourcesInput[]
  updateMany?: Prisma.resource_servicesUpdateManyWithWhereWithoutResourcesInput | Prisma.resource_servicesUpdateManyWithWhereWithoutResourcesInput[]
  deleteMany?: Prisma.resource_servicesScalarWhereInput | Prisma.resource_servicesScalarWhereInput[]
}

export type resource_servicesUncheckedUpdateManyWithoutResourcesNestedInput = {
  create?: Prisma.XOR<Prisma.resource_servicesCreateWithoutResourcesInput, Prisma.resource_servicesUncheckedCreateWithoutResourcesInput> | Prisma.resource_servicesCreateWithoutResourcesInput[] | Prisma.resource_servicesUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.resource_servicesCreateOrConnectWithoutResourcesInput | Prisma.resource_servicesCreateOrConnectWithoutResourcesInput[]
  upsert?: Prisma.resource_servicesUpsertWithWhereUniqueWithoutResourcesInput | Prisma.resource_servicesUpsertWithWhereUniqueWithoutResourcesInput[]
  createMany?: Prisma.resource_servicesCreateManyResourcesInputEnvelope
  set?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  disconnect?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  delete?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  connect?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  update?: Prisma.resource_servicesUpdateWithWhereUniqueWithoutResourcesInput | Prisma.resource_servicesUpdateWithWhereUniqueWithoutResourcesInput[]
  updateMany?: Prisma.resource_servicesUpdateManyWithWhereWithoutResourcesInput | Prisma.resource_servicesUpdateManyWithWhereWithoutResourcesInput[]
  deleteMany?: Prisma.resource_servicesScalarWhereInput | Prisma.resource_servicesScalarWhereInput[]
}

export type resource_servicesUpdateManyWithoutSalon_servicesNestedInput = {
  create?: Prisma.XOR<Prisma.resource_servicesCreateWithoutSalon_servicesInput, Prisma.resource_servicesUncheckedCreateWithoutSalon_servicesInput> | Prisma.resource_servicesCreateWithoutSalon_servicesInput[] | Prisma.resource_servicesUncheckedCreateWithoutSalon_servicesInput[]
  connectOrCreate?: Prisma.resource_servicesCreateOrConnectWithoutSalon_servicesInput | Prisma.resource_servicesCreateOrConnectWithoutSalon_servicesInput[]
  upsert?: Prisma.resource_servicesUpsertWithWhereUniqueWithoutSalon_servicesInput | Prisma.resource_servicesUpsertWithWhereUniqueWithoutSalon_servicesInput[]
  createMany?: Prisma.resource_servicesCreateManySalon_servicesInputEnvelope
  set?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  disconnect?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  delete?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  connect?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  update?: Prisma.resource_servicesUpdateWithWhereUniqueWithoutSalon_servicesInput | Prisma.resource_servicesUpdateWithWhereUniqueWithoutSalon_servicesInput[]
  updateMany?: Prisma.resource_servicesUpdateManyWithWhereWithoutSalon_servicesInput | Prisma.resource_servicesUpdateManyWithWhereWithoutSalon_servicesInput[]
  deleteMany?: Prisma.resource_servicesScalarWhereInput | Prisma.resource_servicesScalarWhereInput[]
}

export type resource_servicesUncheckedUpdateManyWithoutSalon_servicesNestedInput = {
  create?: Prisma.XOR<Prisma.resource_servicesCreateWithoutSalon_servicesInput, Prisma.resource_servicesUncheckedCreateWithoutSalon_servicesInput> | Prisma.resource_servicesCreateWithoutSalon_servicesInput[] | Prisma.resource_servicesUncheckedCreateWithoutSalon_servicesInput[]
  connectOrCreate?: Prisma.resource_servicesCreateOrConnectWithoutSalon_servicesInput | Prisma.resource_servicesCreateOrConnectWithoutSalon_servicesInput[]
  upsert?: Prisma.resource_servicesUpsertWithWhereUniqueWithoutSalon_servicesInput | Prisma.resource_servicesUpsertWithWhereUniqueWithoutSalon_servicesInput[]
  createMany?: Prisma.resource_servicesCreateManySalon_servicesInputEnvelope
  set?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  disconnect?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  delete?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  connect?: Prisma.resource_servicesWhereUniqueInput | Prisma.resource_servicesWhereUniqueInput[]
  update?: Prisma.resource_servicesUpdateWithWhereUniqueWithoutSalon_servicesInput | Prisma.resource_servicesUpdateWithWhereUniqueWithoutSalon_servicesInput[]
  updateMany?: Prisma.resource_servicesUpdateManyWithWhereWithoutSalon_servicesInput | Prisma.resource_servicesUpdateManyWithWhereWithoutSalon_servicesInput[]
  deleteMany?: Prisma.resource_servicesScalarWhereInput | Prisma.resource_servicesScalarWhereInput[]
}

export type resource_servicesCreateWithoutResourcesInput = {
  salon_services: Prisma.salon_servicesCreateNestedOneWithoutResource_servicesInput
}

export type resource_servicesUncheckedCreateWithoutResourcesInput = {
  service_id: number
}

export type resource_servicesCreateOrConnectWithoutResourcesInput = {
  where: Prisma.resource_servicesWhereUniqueInput
  create: Prisma.XOR<Prisma.resource_servicesCreateWithoutResourcesInput, Prisma.resource_servicesUncheckedCreateWithoutResourcesInput>
}

export type resource_servicesCreateManyResourcesInputEnvelope = {
  data: Prisma.resource_servicesCreateManyResourcesInput | Prisma.resource_servicesCreateManyResourcesInput[]
  skipDuplicates?: boolean
}

export type resource_servicesUpsertWithWhereUniqueWithoutResourcesInput = {
  where: Prisma.resource_servicesWhereUniqueInput
  update: Prisma.XOR<Prisma.resource_servicesUpdateWithoutResourcesInput, Prisma.resource_servicesUncheckedUpdateWithoutResourcesInput>
  create: Prisma.XOR<Prisma.resource_servicesCreateWithoutResourcesInput, Prisma.resource_servicesUncheckedCreateWithoutResourcesInput>
}

export type resource_servicesUpdateWithWhereUniqueWithoutResourcesInput = {
  where: Prisma.resource_servicesWhereUniqueInput
  data: Prisma.XOR<Prisma.resource_servicesUpdateWithoutResourcesInput, Prisma.resource_servicesUncheckedUpdateWithoutResourcesInput>
}

export type resource_servicesUpdateManyWithWhereWithoutResourcesInput = {
  where: Prisma.resource_servicesScalarWhereInput
  data: Prisma.XOR<Prisma.resource_servicesUpdateManyMutationInput, Prisma.resource_servicesUncheckedUpdateManyWithoutResourcesInput>
}

export type resource_servicesScalarWhereInput = {
  AND?: Prisma.resource_servicesScalarWhereInput | Prisma.resource_servicesScalarWhereInput[]
  OR?: Prisma.resource_servicesScalarWhereInput[]
  NOT?: Prisma.resource_servicesScalarWhereInput | Prisma.resource_servicesScalarWhereInput[]
  resource_id?: Prisma.IntFilter<"resource_services"> | number
  service_id?: Prisma.IntFilter<"resource_services"> | number
}

export type resource_servicesCreateWithoutSalon_servicesInput = {
  resources: Prisma.resourcesCreateNestedOneWithoutResource_servicesInput
}

export type resource_servicesUncheckedCreateWithoutSalon_servicesInput = {
  resource_id: number
}

export type resource_servicesCreateOrConnectWithoutSalon_servicesInput = {
  where: Prisma.resource_servicesWhereUniqueInput
  create: Prisma.XOR<Prisma.resource_servicesCreateWithoutSalon_servicesInput, Prisma.resource_servicesUncheckedCreateWithoutSalon_servicesInput>
}

export type resource_servicesUpsertWithWhereUniqueWithoutSalon_servicesInput = {
  where: Prisma.resource_servicesWhereUniqueInput
  update: Prisma.XOR<Prisma.resource_servicesUpdateWithoutSalon_servicesInput, Prisma.resource_servicesUncheckedUpdateWithoutSalon_servicesInput>
  create: Prisma.XOR<Prisma.resource_servicesCreateWithoutSalon_servicesInput, Prisma.resource_servicesUncheckedCreateWithoutSalon_servicesInput>
}

export type resource_servicesCreateManySalon_servicesInputEnvelope = {
  data: Prisma.resource_servicesCreateManySalon_servicesInput | Prisma.resource_servicesCreateManySalon_servicesInput[]
  skipDuplicates?: boolean
}

export type resource_servicesUpdateWithWhereUniqueWithoutSalon_servicesInput = {
  where: Prisma.resource_servicesWhereUniqueInput
  data: Prisma.XOR<Prisma.resource_servicesUpdateWithoutSalon_servicesInput, Prisma.resource_servicesUncheckedUpdateWithoutSalon_servicesInput>
}

export type resource_servicesUpdateManyWithWhereWithoutSalon_servicesInput = {
  where: Prisma.resource_servicesScalarWhereInput
  data: Prisma.XOR<Prisma.resource_servicesUpdateManyMutationInput, Prisma.resource_servicesUncheckedUpdateManyWithoutSalon_servicesInput>
}

export type resource_servicesCreateManyResourcesInput = {
  service_id: number
}

export type resource_servicesUpdateWithoutResourcesInput = {
  salon_services?: Prisma.salon_servicesUpdateOneRequiredWithoutResource_servicesNestedInput
}

export type resource_servicesUncheckedUpdateWithoutResourcesInput = {
  service_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type resource_servicesUncheckedUpdateManyWithoutResourcesInput = {
  service_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type resource_servicesUpdateWithoutSalon_servicesInput = {
  resources?: Prisma.resourcesUpdateOneRequiredWithoutResource_servicesNestedInput
}

export type resource_servicesUncheckedUpdateWithoutSalon_servicesInput = {
  resource_id?: Prisma.IntFieldUpdateOperationsInput | number
}

export type resource_servicesCreateManySalon_servicesInput = {
  resource_id: number
}

export type resource_servicesUncheckedUpdateManyWithoutSalon_servicesInput = {
  resource_id?: Prisma.IntFieldUpdateOperationsInput | number
}



export type resource_servicesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  resource_id?: boolean
  service_id?: boolean
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
  salon_services?: boolean | Prisma.salon_servicesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["resource_services"]>

export type resource_servicesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  resource_id?: boolean
  service_id?: boolean
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
  salon_services?: boolean | Prisma.salon_servicesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["resource_services"]>

export type resource_servicesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  resource_id?: boolean
  service_id?: boolean
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
  salon_services?: boolean | Prisma.salon_servicesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["resource_services"]>

export type resource_servicesSelectScalar = {
  resource_id?: boolean
  service_id?: boolean
}

export type resource_servicesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"resource_id" | "service_id", ExtArgs["result"]["resource_services"]>
export type resource_servicesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
  salon_services?: boolean | Prisma.salon_servicesDefaultArgs<ExtArgs>
}
export type resource_servicesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
  salon_services?: boolean | Prisma.salon_servicesDefaultArgs<ExtArgs>
}
export type resource_servicesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
  salon_services?: boolean | Prisma.salon_servicesDefaultArgs<ExtArgs>
}

export type $resource_servicesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "resource_services"
  objects: {
    resources: Prisma.$resourcesPayload<ExtArgs>
    salon_services: Prisma.$salon_servicesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    resource_id: number
    service_id: number
  }, ExtArgs["result"]["resource_services"]>
  composites: {}
}

export type resource_servicesGetPayload<S extends boolean | null | undefined | resource_servicesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$resource_servicesPayload, S>

export type resource_servicesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<resource_servicesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Resource_servicesCountAggregateInputType | true
  }

export interface resource_servicesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['resource_services'], meta: { name: 'resource_services' } }
  /**
   * Find zero or one Resource_services that matches the filter.
   * @param {resource_servicesFindUniqueArgs} args - Arguments to find a Resource_services
   * @example
   * // Get one Resource_services
   * const resource_services = await prisma.resource_services.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends resource_servicesFindUniqueArgs>(args: Prisma.SelectSubset<T, resource_servicesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__resource_servicesClient<runtime.Types.Result.GetResult<Prisma.$resource_servicesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Resource_services that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {resource_servicesFindUniqueOrThrowArgs} args - Arguments to find a Resource_services
   * @example
   * // Get one Resource_services
   * const resource_services = await prisma.resource_services.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends resource_servicesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, resource_servicesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__resource_servicesClient<runtime.Types.Result.GetResult<Prisma.$resource_servicesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Resource_services that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {resource_servicesFindFirstArgs} args - Arguments to find a Resource_services
   * @example
   * // Get one Resource_services
   * const resource_services = await prisma.resource_services.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends resource_servicesFindFirstArgs>(args?: Prisma.SelectSubset<T, resource_servicesFindFirstArgs<ExtArgs>>): Prisma.Prisma__resource_servicesClient<runtime.Types.Result.GetResult<Prisma.$resource_servicesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Resource_services that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {resource_servicesFindFirstOrThrowArgs} args - Arguments to find a Resource_services
   * @example
   * // Get one Resource_services
   * const resource_services = await prisma.resource_services.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends resource_servicesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, resource_servicesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__resource_servicesClient<runtime.Types.Result.GetResult<Prisma.$resource_servicesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Resource_services that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {resource_servicesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Resource_services
   * const resource_services = await prisma.resource_services.findMany()
   * 
   * // Get first 10 Resource_services
   * const resource_services = await prisma.resource_services.findMany({ take: 10 })
   * 
   * // Only select the `resource_id`
   * const resource_servicesWithResource_idOnly = await prisma.resource_services.findMany({ select: { resource_id: true } })
   * 
   */
  findMany<T extends resource_servicesFindManyArgs>(args?: Prisma.SelectSubset<T, resource_servicesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$resource_servicesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Resource_services.
   * @param {resource_servicesCreateArgs} args - Arguments to create a Resource_services.
   * @example
   * // Create one Resource_services
   * const Resource_services = await prisma.resource_services.create({
   *   data: {
   *     // ... data to create a Resource_services
   *   }
   * })
   * 
   */
  create<T extends resource_servicesCreateArgs>(args: Prisma.SelectSubset<T, resource_servicesCreateArgs<ExtArgs>>): Prisma.Prisma__resource_servicesClient<runtime.Types.Result.GetResult<Prisma.$resource_servicesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Resource_services.
   * @param {resource_servicesCreateManyArgs} args - Arguments to create many Resource_services.
   * @example
   * // Create many Resource_services
   * const resource_services = await prisma.resource_services.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends resource_servicesCreateManyArgs>(args?: Prisma.SelectSubset<T, resource_servicesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Resource_services and returns the data saved in the database.
   * @param {resource_servicesCreateManyAndReturnArgs} args - Arguments to create many Resource_services.
   * @example
   * // Create many Resource_services
   * const resource_services = await prisma.resource_services.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Resource_services and only return the `resource_id`
   * const resource_servicesWithResource_idOnly = await prisma.resource_services.createManyAndReturn({
   *   select: { resource_id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends resource_servicesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, resource_servicesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$resource_servicesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Resource_services.
   * @param {resource_servicesDeleteArgs} args - Arguments to delete one Resource_services.
   * @example
   * // Delete one Resource_services
   * const Resource_services = await prisma.resource_services.delete({
   *   where: {
   *     // ... filter to delete one Resource_services
   *   }
   * })
   * 
   */
  delete<T extends resource_servicesDeleteArgs>(args: Prisma.SelectSubset<T, resource_servicesDeleteArgs<ExtArgs>>): Prisma.Prisma__resource_servicesClient<runtime.Types.Result.GetResult<Prisma.$resource_servicesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Resource_services.
   * @param {resource_servicesUpdateArgs} args - Arguments to update one Resource_services.
   * @example
   * // Update one Resource_services
   * const resource_services = await prisma.resource_services.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends resource_servicesUpdateArgs>(args: Prisma.SelectSubset<T, resource_servicesUpdateArgs<ExtArgs>>): Prisma.Prisma__resource_servicesClient<runtime.Types.Result.GetResult<Prisma.$resource_servicesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Resource_services.
   * @param {resource_servicesDeleteManyArgs} args - Arguments to filter Resource_services to delete.
   * @example
   * // Delete a few Resource_services
   * const { count } = await prisma.resource_services.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends resource_servicesDeleteManyArgs>(args?: Prisma.SelectSubset<T, resource_servicesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Resource_services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {resource_servicesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Resource_services
   * const resource_services = await prisma.resource_services.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends resource_servicesUpdateManyArgs>(args: Prisma.SelectSubset<T, resource_servicesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Resource_services and returns the data updated in the database.
   * @param {resource_servicesUpdateManyAndReturnArgs} args - Arguments to update many Resource_services.
   * @example
   * // Update many Resource_services
   * const resource_services = await prisma.resource_services.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Resource_services and only return the `resource_id`
   * const resource_servicesWithResource_idOnly = await prisma.resource_services.updateManyAndReturn({
   *   select: { resource_id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends resource_servicesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, resource_servicesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$resource_servicesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Resource_services.
   * @param {resource_servicesUpsertArgs} args - Arguments to update or create a Resource_services.
   * @example
   * // Update or create a Resource_services
   * const resource_services = await prisma.resource_services.upsert({
   *   create: {
   *     // ... data to create a Resource_services
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Resource_services we want to update
   *   }
   * })
   */
  upsert<T extends resource_servicesUpsertArgs>(args: Prisma.SelectSubset<T, resource_servicesUpsertArgs<ExtArgs>>): Prisma.Prisma__resource_servicesClient<runtime.Types.Result.GetResult<Prisma.$resource_servicesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Resource_services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {resource_servicesCountArgs} args - Arguments to filter Resource_services to count.
   * @example
   * // Count the number of Resource_services
   * const count = await prisma.resource_services.count({
   *   where: {
   *     // ... the filter for the Resource_services we want to count
   *   }
   * })
  **/
  count<T extends resource_servicesCountArgs>(
    args?: Prisma.Subset<T, resource_servicesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Resource_servicesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Resource_services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Resource_servicesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Resource_servicesAggregateArgs>(args: Prisma.Subset<T, Resource_servicesAggregateArgs>): Prisma.PrismaPromise<GetResource_servicesAggregateType<T>>

  /**
   * Group by Resource_services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {resource_servicesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends resource_servicesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: resource_servicesGroupByArgs['orderBy'] }
      : { orderBy?: resource_servicesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, resource_servicesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetResource_servicesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the resource_services model
 */
readonly fields: resource_servicesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for resource_services.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__resource_servicesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  resources<T extends Prisma.resourcesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.resourcesDefaultArgs<ExtArgs>>): Prisma.Prisma__resourcesClient<runtime.Types.Result.GetResult<Prisma.$resourcesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  salon_services<T extends Prisma.salon_servicesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.salon_servicesDefaultArgs<ExtArgs>>): Prisma.Prisma__salon_servicesClient<runtime.Types.Result.GetResult<Prisma.$salon_servicesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the resource_services model
 */
export interface resource_servicesFieldRefs {
  readonly resource_id: Prisma.FieldRef<"resource_services", 'Int'>
  readonly service_id: Prisma.FieldRef<"resource_services", 'Int'>
}
    

// Custom InputTypes
/**
 * resource_services findUnique
 */
export type resource_servicesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the resource_services
   */
  select?: Prisma.resource_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the resource_services
   */
  omit?: Prisma.resource_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.resource_servicesInclude<ExtArgs> | null
  /**
   * Filter, which resource_services to fetch.
   */
  where: Prisma.resource_servicesWhereUniqueInput
}

/**
 * resource_services findUniqueOrThrow
 */
export type resource_servicesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the resource_services
   */
  select?: Prisma.resource_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the resource_services
   */
  omit?: Prisma.resource_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.resource_servicesInclude<ExtArgs> | null
  /**
   * Filter, which resource_services to fetch.
   */
  where: Prisma.resource_servicesWhereUniqueInput
}

/**
 * resource_services findFirst
 */
export type resource_servicesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the resource_services
   */
  select?: Prisma.resource_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the resource_services
   */
  omit?: Prisma.resource_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.resource_servicesInclude<ExtArgs> | null
  /**
   * Filter, which resource_services to fetch.
   */
  where?: Prisma.resource_servicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of resource_services to fetch.
   */
  orderBy?: Prisma.resource_servicesOrderByWithRelationInput | Prisma.resource_servicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for resource_services.
   */
  cursor?: Prisma.resource_servicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` resource_services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` resource_services.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of resource_services.
   */
  distinct?: Prisma.Resource_servicesScalarFieldEnum | Prisma.Resource_servicesScalarFieldEnum[]
}

/**
 * resource_services findFirstOrThrow
 */
export type resource_servicesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the resource_services
   */
  select?: Prisma.resource_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the resource_services
   */
  omit?: Prisma.resource_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.resource_servicesInclude<ExtArgs> | null
  /**
   * Filter, which resource_services to fetch.
   */
  where?: Prisma.resource_servicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of resource_services to fetch.
   */
  orderBy?: Prisma.resource_servicesOrderByWithRelationInput | Prisma.resource_servicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for resource_services.
   */
  cursor?: Prisma.resource_servicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` resource_services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` resource_services.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of resource_services.
   */
  distinct?: Prisma.Resource_servicesScalarFieldEnum | Prisma.Resource_servicesScalarFieldEnum[]
}

/**
 * resource_services findMany
 */
export type resource_servicesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the resource_services
   */
  select?: Prisma.resource_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the resource_services
   */
  omit?: Prisma.resource_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.resource_servicesInclude<ExtArgs> | null
  /**
   * Filter, which resource_services to fetch.
   */
  where?: Prisma.resource_servicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of resource_services to fetch.
   */
  orderBy?: Prisma.resource_servicesOrderByWithRelationInput | Prisma.resource_servicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing resource_services.
   */
  cursor?: Prisma.resource_servicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` resource_services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` resource_services.
   */
  skip?: number
  distinct?: Prisma.Resource_servicesScalarFieldEnum | Prisma.Resource_servicesScalarFieldEnum[]
}

/**
 * resource_services create
 */
export type resource_servicesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the resource_services
   */
  select?: Prisma.resource_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the resource_services
   */
  omit?: Prisma.resource_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.resource_servicesInclude<ExtArgs> | null
  /**
   * The data needed to create a resource_services.
   */
  data: Prisma.XOR<Prisma.resource_servicesCreateInput, Prisma.resource_servicesUncheckedCreateInput>
}

/**
 * resource_services createMany
 */
export type resource_servicesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many resource_services.
   */
  data: Prisma.resource_servicesCreateManyInput | Prisma.resource_servicesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * resource_services createManyAndReturn
 */
export type resource_servicesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the resource_services
   */
  select?: Prisma.resource_servicesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the resource_services
   */
  omit?: Prisma.resource_servicesOmit<ExtArgs> | null
  /**
   * The data used to create many resource_services.
   */
  data: Prisma.resource_servicesCreateManyInput | Prisma.resource_servicesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.resource_servicesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * resource_services update
 */
export type resource_servicesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the resource_services
   */
  select?: Prisma.resource_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the resource_services
   */
  omit?: Prisma.resource_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.resource_servicesInclude<ExtArgs> | null
  /**
   * The data needed to update a resource_services.
   */
  data: Prisma.XOR<Prisma.resource_servicesUpdateInput, Prisma.resource_servicesUncheckedUpdateInput>
  /**
   * Choose, which resource_services to update.
   */
  where: Prisma.resource_servicesWhereUniqueInput
}

/**
 * resource_services updateMany
 */
export type resource_servicesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update resource_services.
   */
  data: Prisma.XOR<Prisma.resource_servicesUpdateManyMutationInput, Prisma.resource_servicesUncheckedUpdateManyInput>
  /**
   * Filter which resource_services to update
   */
  where?: Prisma.resource_servicesWhereInput
  /**
   * Limit how many resource_services to update.
   */
  limit?: number
}

/**
 * resource_services updateManyAndReturn
 */
export type resource_servicesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the resource_services
   */
  select?: Prisma.resource_servicesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the resource_services
   */
  omit?: Prisma.resource_servicesOmit<ExtArgs> | null
  /**
   * The data used to update resource_services.
   */
  data: Prisma.XOR<Prisma.resource_servicesUpdateManyMutationInput, Prisma.resource_servicesUncheckedUpdateManyInput>
  /**
   * Filter which resource_services to update
   */
  where?: Prisma.resource_servicesWhereInput
  /**
   * Limit how many resource_services to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.resource_servicesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * resource_services upsert
 */
export type resource_servicesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the resource_services
   */
  select?: Prisma.resource_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the resource_services
   */
  omit?: Prisma.resource_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.resource_servicesInclude<ExtArgs> | null
  /**
   * The filter to search for the resource_services to update in case it exists.
   */
  where: Prisma.resource_servicesWhereUniqueInput
  /**
   * In case the resource_services found by the `where` argument doesn't exist, create a new resource_services with this data.
   */
  create: Prisma.XOR<Prisma.resource_servicesCreateInput, Prisma.resource_servicesUncheckedCreateInput>
  /**
   * In case the resource_services was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.resource_servicesUpdateInput, Prisma.resource_servicesUncheckedUpdateInput>
}

/**
 * resource_services delete
 */
export type resource_servicesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the resource_services
   */
  select?: Prisma.resource_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the resource_services
   */
  omit?: Prisma.resource_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.resource_servicesInclude<ExtArgs> | null
  /**
   * Filter which resource_services to delete.
   */
  where: Prisma.resource_servicesWhereUniqueInput
}

/**
 * resource_services deleteMany
 */
export type resource_servicesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which resource_services to delete
   */
  where?: Prisma.resource_servicesWhereInput
  /**
   * Limit how many resource_services to delete.
   */
  limit?: number
}

/**
 * resource_services without action
 */
export type resource_servicesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the resource_services
   */
  select?: Prisma.resource_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the resource_services
   */
  omit?: Prisma.resource_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.resource_servicesInclude<ExtArgs> | null
}
