
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `salon_services` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model salon_services
 * 
 */
export type salon_servicesModel = runtime.Types.Result.DefaultSelection<Prisma.$salon_servicesPayload>

export type AggregateSalon_services = {
  _count: Salon_servicesCountAggregateOutputType | null
  _avg: Salon_servicesAvgAggregateOutputType | null
  _sum: Salon_servicesSumAggregateOutputType | null
  _min: Salon_servicesMinAggregateOutputType | null
  _max: Salon_servicesMaxAggregateOutputType | null
}

export type Salon_servicesAvgAggregateOutputType = {
  id: number | null
  price: runtime.Decimal | null
}

export type Salon_servicesSumAggregateOutputType = {
  id: number | null
  price: runtime.Decimal | null
}

export type Salon_servicesMinAggregateOutputType = {
  id: number | null
  name: string | null
  price: runtime.Decimal | null
  active: boolean | null
}

export type Salon_servicesMaxAggregateOutputType = {
  id: number | null
  name: string | null
  price: runtime.Decimal | null
  active: boolean | null
}

export type Salon_servicesCountAggregateOutputType = {
  id: number
  name: number
  price: number
  active: number
  _all: number
}


export type Salon_servicesAvgAggregateInputType = {
  id?: true
  price?: true
}

export type Salon_servicesSumAggregateInputType = {
  id?: true
  price?: true
}

export type Salon_servicesMinAggregateInputType = {
  id?: true
  name?: true
  price?: true
  active?: true
}

export type Salon_servicesMaxAggregateInputType = {
  id?: true
  name?: true
  price?: true
  active?: true
}

export type Salon_servicesCountAggregateInputType = {
  id?: true
  name?: true
  price?: true
  active?: true
  _all?: true
}

export type Salon_servicesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which salon_services to aggregate.
   */
  where?: Prisma.salon_servicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of salon_services to fetch.
   */
  orderBy?: Prisma.salon_servicesOrderByWithRelationInput | Prisma.salon_servicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.salon_servicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` salon_services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` salon_services.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned salon_services
  **/
  _count?: true | Salon_servicesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Salon_servicesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Salon_servicesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Salon_servicesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Salon_servicesMaxAggregateInputType
}

export type GetSalon_servicesAggregateType<T extends Salon_servicesAggregateArgs> = {
      [P in keyof T & keyof AggregateSalon_services]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSalon_services[P]>
    : Prisma.GetScalarType<T[P], AggregateSalon_services[P]>
}




export type salon_servicesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.salon_servicesWhereInput
  orderBy?: Prisma.salon_servicesOrderByWithAggregationInput | Prisma.salon_servicesOrderByWithAggregationInput[]
  by: Prisma.Salon_servicesScalarFieldEnum[] | Prisma.Salon_servicesScalarFieldEnum
  having?: Prisma.salon_servicesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Salon_servicesCountAggregateInputType | true
  _avg?: Salon_servicesAvgAggregateInputType
  _sum?: Salon_servicesSumAggregateInputType
  _min?: Salon_servicesMinAggregateInputType
  _max?: Salon_servicesMaxAggregateInputType
}

export type Salon_servicesGroupByOutputType = {
  id: number
  name: string
  price: runtime.Decimal
  active: boolean
  _count: Salon_servicesCountAggregateOutputType | null
  _avg: Salon_servicesAvgAggregateOutputType | null
  _sum: Salon_servicesSumAggregateOutputType | null
  _min: Salon_servicesMinAggregateOutputType | null
  _max: Salon_servicesMaxAggregateOutputType | null
}

type GetSalon_servicesGroupByPayload<T extends salon_servicesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Salon_servicesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Salon_servicesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Salon_servicesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Salon_servicesGroupByOutputType[P]>
      }
    >
  >



export type salon_servicesWhereInput = {
  AND?: Prisma.salon_servicesWhereInput | Prisma.salon_servicesWhereInput[]
  OR?: Prisma.salon_servicesWhereInput[]
  NOT?: Prisma.salon_servicesWhereInput | Prisma.salon_servicesWhereInput[]
  id?: Prisma.IntFilter<"salon_services"> | number
  name?: Prisma.StringFilter<"salon_services"> | string
  price?: Prisma.DecimalFilter<"salon_services"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFilter<"salon_services"> | boolean
  bookings?: Prisma.BookingsListRelationFilter
  resource_services?: Prisma.Resource_servicesListRelationFilter
}

export type salon_servicesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  active?: Prisma.SortOrder
  bookings?: Prisma.bookingsOrderByRelationAggregateInput
  resource_services?: Prisma.resource_servicesOrderByRelationAggregateInput
}

export type salon_servicesWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.salon_servicesWhereInput | Prisma.salon_servicesWhereInput[]
  OR?: Prisma.salon_servicesWhereInput[]
  NOT?: Prisma.salon_servicesWhereInput | Prisma.salon_servicesWhereInput[]
  name?: Prisma.StringFilter<"salon_services"> | string
  price?: Prisma.DecimalFilter<"salon_services"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFilter<"salon_services"> | boolean
  bookings?: Prisma.BookingsListRelationFilter
  resource_services?: Prisma.Resource_servicesListRelationFilter
}, "id">

export type salon_servicesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  active?: Prisma.SortOrder
  _count?: Prisma.salon_servicesCountOrderByAggregateInput
  _avg?: Prisma.salon_servicesAvgOrderByAggregateInput
  _max?: Prisma.salon_servicesMaxOrderByAggregateInput
  _min?: Prisma.salon_servicesMinOrderByAggregateInput
  _sum?: Prisma.salon_servicesSumOrderByAggregateInput
}

export type salon_servicesScalarWhereWithAggregatesInput = {
  AND?: Prisma.salon_servicesScalarWhereWithAggregatesInput | Prisma.salon_servicesScalarWhereWithAggregatesInput[]
  OR?: Prisma.salon_servicesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.salon_servicesScalarWhereWithAggregatesInput | Prisma.salon_servicesScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"salon_services"> | number
  name?: Prisma.StringWithAggregatesFilter<"salon_services"> | string
  price?: Prisma.DecimalWithAggregatesFilter<"salon_services"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolWithAggregatesFilter<"salon_services"> | boolean
}

export type salon_servicesUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bookings?: Prisma.bookingsUpdateManyWithoutSalon_servicesNestedInput
  resource_services?: Prisma.resource_servicesUpdateManyWithoutSalon_servicesNestedInput
}

export type salon_servicesUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bookings?: Prisma.bookingsUncheckedUpdateManyWithoutSalon_servicesNestedInput
  resource_services?: Prisma.resource_servicesUncheckedUpdateManyWithoutSalon_servicesNestedInput
}

export type salon_servicesUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type salon_servicesUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type Salon_servicesNullableScalarRelationFilter = {
  is?: Prisma.salon_servicesWhereInput | null
  isNot?: Prisma.salon_servicesWhereInput | null
}

export type Salon_servicesScalarRelationFilter = {
  is?: Prisma.salon_servicesWhereInput
  isNot?: Prisma.salon_servicesWhereInput
}

export type salon_servicesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  active?: Prisma.SortOrder
}

export type salon_servicesAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type salon_servicesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  active?: Prisma.SortOrder
}

export type salon_servicesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  active?: Prisma.SortOrder
}

export type salon_servicesSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type salon_servicesCreateNestedOneWithoutBookingsInput = {
  connect?: Prisma.salon_servicesWhereUniqueInput
}

export type salon_servicesUpdateOneWithoutBookingsNestedInput = {
  disconnect?: Prisma.salon_servicesWhereInput | boolean
  delete?: Prisma.salon_servicesWhereInput | boolean
  connect?: Prisma.salon_servicesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.salon_servicesUpdateToOneWithWhereWithoutBookingsInput, Prisma.salon_servicesUpdateWithoutBookingsInput>, Prisma.salon_servicesUncheckedUpdateWithoutBookingsInput>
}

export type salon_servicesCreateNestedOneWithoutResource_servicesInput = {
  connect?: Prisma.salon_servicesWhereUniqueInput
}

export type salon_servicesUpdateOneRequiredWithoutResource_servicesNestedInput = {
  connect?: Prisma.salon_servicesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.salon_servicesUpdateToOneWithWhereWithoutResource_servicesInput, Prisma.salon_servicesUpdateWithoutResource_servicesInput>, Prisma.salon_servicesUncheckedUpdateWithoutResource_servicesInput>
}

export type salon_servicesUpdateToOneWithWhereWithoutBookingsInput = {
  where?: Prisma.salon_servicesWhereInput
  data: Prisma.XOR<Prisma.salon_servicesUpdateWithoutBookingsInput, Prisma.salon_servicesUncheckedUpdateWithoutBookingsInput>
}

export type salon_servicesUpdateWithoutBookingsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  resource_services?: Prisma.resource_servicesUpdateManyWithoutSalon_servicesNestedInput
}

export type salon_servicesUncheckedUpdateWithoutBookingsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  resource_services?: Prisma.resource_servicesUncheckedUpdateManyWithoutSalon_servicesNestedInput
}

export type salon_servicesUpdateToOneWithWhereWithoutResource_servicesInput = {
  where?: Prisma.salon_servicesWhereInput
  data: Prisma.XOR<Prisma.salon_servicesUpdateWithoutResource_servicesInput, Prisma.salon_servicesUncheckedUpdateWithoutResource_servicesInput>
}

export type salon_servicesUpdateWithoutResource_servicesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bookings?: Prisma.bookingsUpdateManyWithoutSalon_servicesNestedInput
}

export type salon_servicesUncheckedUpdateWithoutResource_servicesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  bookings?: Prisma.bookingsUncheckedUpdateManyWithoutSalon_servicesNestedInput
}


/**
 * Count Type Salon_servicesCountOutputType
 */

export type Salon_servicesCountOutputType = {
  bookings: number
  resource_services: number
}

export type Salon_servicesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bookings?: boolean | Salon_servicesCountOutputTypeCountBookingsArgs
  resource_services?: boolean | Salon_servicesCountOutputTypeCountResource_servicesArgs
}

/**
 * Salon_servicesCountOutputType without action
 */
export type Salon_servicesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Salon_servicesCountOutputType
   */
  select?: Prisma.Salon_servicesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Salon_servicesCountOutputType without action
 */
export type Salon_servicesCountOutputTypeCountBookingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.bookingsWhereInput
}

/**
 * Salon_servicesCountOutputType without action
 */
export type Salon_servicesCountOutputTypeCountResource_servicesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.resource_servicesWhereInput
}


export type salon_servicesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
  active?: boolean
  bookings?: boolean | Prisma.salon_services$bookingsArgs<ExtArgs>
  resource_services?: boolean | Prisma.salon_services$resource_servicesArgs<ExtArgs>
  _count?: boolean | Prisma.Salon_servicesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["salon_services"]>


export type salon_servicesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
  active?: boolean
}, ExtArgs["result"]["salon_services"]>

export type salon_servicesSelectScalar = {
  id?: boolean
  name?: boolean
  price?: boolean
  active?: boolean
}

export type salon_servicesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "price" | "active", ExtArgs["result"]["salon_services"]>
export type salon_servicesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bookings?: boolean | Prisma.salon_services$bookingsArgs<ExtArgs>
  resource_services?: boolean | Prisma.salon_services$resource_servicesArgs<ExtArgs>
  _count?: boolean | Prisma.Salon_servicesCountOutputTypeDefaultArgs<ExtArgs>
}
export type salon_servicesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $salon_servicesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "salon_services"
  objects: {
    bookings: Prisma.$bookingsPayload<ExtArgs>[]
    resource_services: Prisma.$resource_servicesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    price: runtime.Decimal
    active: boolean
  }, ExtArgs["result"]["salon_services"]>
  composites: {}
}

export type salon_servicesGetPayload<S extends boolean | null | undefined | salon_servicesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$salon_servicesPayload, S>

export type salon_servicesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<salon_servicesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Salon_servicesCountAggregateInputType | true
  }

export interface salon_servicesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['salon_services'], meta: { name: 'salon_services' } }
  /**
   * Find zero or one Salon_services that matches the filter.
   * @param {salon_servicesFindUniqueArgs} args - Arguments to find a Salon_services
   * @example
   * // Get one Salon_services
   * const salon_services = await prisma.salon_services.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends salon_servicesFindUniqueArgs>(args: Prisma.SelectSubset<T, salon_servicesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__salon_servicesClient<runtime.Types.Result.GetResult<Prisma.$salon_servicesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Salon_services that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {salon_servicesFindUniqueOrThrowArgs} args - Arguments to find a Salon_services
   * @example
   * // Get one Salon_services
   * const salon_services = await prisma.salon_services.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends salon_servicesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, salon_servicesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__salon_servicesClient<runtime.Types.Result.GetResult<Prisma.$salon_servicesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Salon_services that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {salon_servicesFindFirstArgs} args - Arguments to find a Salon_services
   * @example
   * // Get one Salon_services
   * const salon_services = await prisma.salon_services.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends salon_servicesFindFirstArgs>(args?: Prisma.SelectSubset<T, salon_servicesFindFirstArgs<ExtArgs>>): Prisma.Prisma__salon_servicesClient<runtime.Types.Result.GetResult<Prisma.$salon_servicesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Salon_services that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {salon_servicesFindFirstOrThrowArgs} args - Arguments to find a Salon_services
   * @example
   * // Get one Salon_services
   * const salon_services = await prisma.salon_services.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends salon_servicesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, salon_servicesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__salon_servicesClient<runtime.Types.Result.GetResult<Prisma.$salon_servicesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Salon_services that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {salon_servicesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Salon_services
   * const salon_services = await prisma.salon_services.findMany()
   * 
   * // Get first 10 Salon_services
   * const salon_services = await prisma.salon_services.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const salon_servicesWithIdOnly = await prisma.salon_services.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends salon_servicesFindManyArgs>(args?: Prisma.SelectSubset<T, salon_servicesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$salon_servicesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Delete a Salon_services.
   * @param {salon_servicesDeleteArgs} args - Arguments to delete one Salon_services.
   * @example
   * // Delete one Salon_services
   * const Salon_services = await prisma.salon_services.delete({
   *   where: {
   *     // ... filter to delete one Salon_services
   *   }
   * })
   * 
   */
  delete<T extends salon_servicesDeleteArgs>(args: Prisma.SelectSubset<T, salon_servicesDeleteArgs<ExtArgs>>): Prisma.Prisma__salon_servicesClient<runtime.Types.Result.GetResult<Prisma.$salon_servicesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Salon_services.
   * @param {salon_servicesUpdateArgs} args - Arguments to update one Salon_services.
   * @example
   * // Update one Salon_services
   * const salon_services = await prisma.salon_services.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends salon_servicesUpdateArgs>(args: Prisma.SelectSubset<T, salon_servicesUpdateArgs<ExtArgs>>): Prisma.Prisma__salon_servicesClient<runtime.Types.Result.GetResult<Prisma.$salon_servicesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Salon_services.
   * @param {salon_servicesDeleteManyArgs} args - Arguments to filter Salon_services to delete.
   * @example
   * // Delete a few Salon_services
   * const { count } = await prisma.salon_services.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends salon_servicesDeleteManyArgs>(args?: Prisma.SelectSubset<T, salon_servicesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Salon_services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {salon_servicesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Salon_services
   * const salon_services = await prisma.salon_services.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends salon_servicesUpdateManyArgs>(args: Prisma.SelectSubset<T, salon_servicesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Salon_services and returns the data updated in the database.
   * @param {salon_servicesUpdateManyAndReturnArgs} args - Arguments to update many Salon_services.
   * @example
   * // Update many Salon_services
   * const salon_services = await prisma.salon_services.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Salon_services and only return the `id`
   * const salon_servicesWithIdOnly = await prisma.salon_services.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends salon_servicesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, salon_servicesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$salon_servicesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>


  /**
   * Count the number of Salon_services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {salon_servicesCountArgs} args - Arguments to filter Salon_services to count.
   * @example
   * // Count the number of Salon_services
   * const count = await prisma.salon_services.count({
   *   where: {
   *     // ... the filter for the Salon_services we want to count
   *   }
   * })
  **/
  count<T extends salon_servicesCountArgs>(
    args?: Prisma.Subset<T, salon_servicesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Salon_servicesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Salon_services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Salon_servicesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Salon_servicesAggregateArgs>(args: Prisma.Subset<T, Salon_servicesAggregateArgs>): Prisma.PrismaPromise<GetSalon_servicesAggregateType<T>>

  /**
   * Group by Salon_services.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {salon_servicesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends salon_servicesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: salon_servicesGroupByArgs['orderBy'] }
      : { orderBy?: salon_servicesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, salon_servicesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSalon_servicesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the salon_services model
 */
readonly fields: salon_servicesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for salon_services.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__salon_servicesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bookings<T extends Prisma.salon_services$bookingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.salon_services$bookingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$bookingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  resource_services<T extends Prisma.salon_services$resource_servicesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.salon_services$resource_servicesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$resource_servicesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the salon_services model
 */
export interface salon_servicesFieldRefs {
  readonly id: Prisma.FieldRef<"salon_services", 'Int'>
  readonly name: Prisma.FieldRef<"salon_services", 'String'>
  readonly price: Prisma.FieldRef<"salon_services", 'Decimal'>
  readonly active: Prisma.FieldRef<"salon_services", 'Boolean'>
}
    

// Custom InputTypes
/**
 * salon_services findUnique
 */
export type salon_servicesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the salon_services
   */
  select?: Prisma.salon_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the salon_services
   */
  omit?: Prisma.salon_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.salon_servicesInclude<ExtArgs> | null
  /**
   * Filter, which salon_services to fetch.
   */
  where: Prisma.salon_servicesWhereUniqueInput
}

/**
 * salon_services findUniqueOrThrow
 */
export type salon_servicesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the salon_services
   */
  select?: Prisma.salon_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the salon_services
   */
  omit?: Prisma.salon_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.salon_servicesInclude<ExtArgs> | null
  /**
   * Filter, which salon_services to fetch.
   */
  where: Prisma.salon_servicesWhereUniqueInput
}

/**
 * salon_services findFirst
 */
export type salon_servicesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the salon_services
   */
  select?: Prisma.salon_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the salon_services
   */
  omit?: Prisma.salon_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.salon_servicesInclude<ExtArgs> | null
  /**
   * Filter, which salon_services to fetch.
   */
  where?: Prisma.salon_servicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of salon_services to fetch.
   */
  orderBy?: Prisma.salon_servicesOrderByWithRelationInput | Prisma.salon_servicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for salon_services.
   */
  cursor?: Prisma.salon_servicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` salon_services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` salon_services.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of salon_services.
   */
  distinct?: Prisma.Salon_servicesScalarFieldEnum | Prisma.Salon_servicesScalarFieldEnum[]
}

/**
 * salon_services findFirstOrThrow
 */
export type salon_servicesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the salon_services
   */
  select?: Prisma.salon_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the salon_services
   */
  omit?: Prisma.salon_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.salon_servicesInclude<ExtArgs> | null
  /**
   * Filter, which salon_services to fetch.
   */
  where?: Prisma.salon_servicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of salon_services to fetch.
   */
  orderBy?: Prisma.salon_servicesOrderByWithRelationInput | Prisma.salon_servicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for salon_services.
   */
  cursor?: Prisma.salon_servicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` salon_services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` salon_services.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of salon_services.
   */
  distinct?: Prisma.Salon_servicesScalarFieldEnum | Prisma.Salon_servicesScalarFieldEnum[]
}

/**
 * salon_services findMany
 */
export type salon_servicesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the salon_services
   */
  select?: Prisma.salon_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the salon_services
   */
  omit?: Prisma.salon_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.salon_servicesInclude<ExtArgs> | null
  /**
   * Filter, which salon_services to fetch.
   */
  where?: Prisma.salon_servicesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of salon_services to fetch.
   */
  orderBy?: Prisma.salon_servicesOrderByWithRelationInput | Prisma.salon_servicesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing salon_services.
   */
  cursor?: Prisma.salon_servicesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` salon_services from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` salon_services.
   */
  skip?: number
  distinct?: Prisma.Salon_servicesScalarFieldEnum | Prisma.Salon_servicesScalarFieldEnum[]
}

/**
 * salon_services update
 */
export type salon_servicesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the salon_services
   */
  select?: Prisma.salon_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the salon_services
   */
  omit?: Prisma.salon_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.salon_servicesInclude<ExtArgs> | null
  /**
   * The data needed to update a salon_services.
   */
  data: Prisma.XOR<Prisma.salon_servicesUpdateInput, Prisma.salon_servicesUncheckedUpdateInput>
  /**
   * Choose, which salon_services to update.
   */
  where: Prisma.salon_servicesWhereUniqueInput
}

/**
 * salon_services updateMany
 */
export type salon_servicesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update salon_services.
   */
  data: Prisma.XOR<Prisma.salon_servicesUpdateManyMutationInput, Prisma.salon_servicesUncheckedUpdateManyInput>
  /**
   * Filter which salon_services to update
   */
  where?: Prisma.salon_servicesWhereInput
  /**
   * Limit how many salon_services to update.
   */
  limit?: number
}

/**
 * salon_services updateManyAndReturn
 */
export type salon_servicesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the salon_services
   */
  select?: Prisma.salon_servicesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the salon_services
   */
  omit?: Prisma.salon_servicesOmit<ExtArgs> | null
  /**
   * The data used to update salon_services.
   */
  data: Prisma.XOR<Prisma.salon_servicesUpdateManyMutationInput, Prisma.salon_servicesUncheckedUpdateManyInput>
  /**
   * Filter which salon_services to update
   */
  where?: Prisma.salon_servicesWhereInput
  /**
   * Limit how many salon_services to update.
   */
  limit?: number
}

/**
 * salon_services delete
 */
export type salon_servicesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the salon_services
   */
  select?: Prisma.salon_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the salon_services
   */
  omit?: Prisma.salon_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.salon_servicesInclude<ExtArgs> | null
  /**
   * Filter which salon_services to delete.
   */
  where: Prisma.salon_servicesWhereUniqueInput
}

/**
 * salon_services deleteMany
 */
export type salon_servicesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which salon_services to delete
   */
  where?: Prisma.salon_servicesWhereInput
  /**
   * Limit how many salon_services to delete.
   */
  limit?: number
}

/**
 * salon_services.bookings
 */
export type salon_services$bookingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the bookings
   */
  select?: Prisma.bookingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the bookings
   */
  omit?: Prisma.bookingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.bookingsInclude<ExtArgs> | null
  where?: Prisma.bookingsWhereInput
  orderBy?: Prisma.bookingsOrderByWithRelationInput | Prisma.bookingsOrderByWithRelationInput[]
  cursor?: Prisma.bookingsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BookingsScalarFieldEnum | Prisma.BookingsScalarFieldEnum[]
}

/**
 * salon_services.resource_services
 */
export type salon_services$resource_servicesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the resource_services
   */
  select?: Prisma.resource_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the resource_services
   */
  omit?: Prisma.resource_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.resource_servicesInclude<ExtArgs> | null
  where?: Prisma.resource_servicesWhereInput
  orderBy?: Prisma.resource_servicesOrderByWithRelationInput | Prisma.resource_servicesOrderByWithRelationInput[]
  cursor?: Prisma.resource_servicesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Resource_servicesScalarFieldEnum | Prisma.Resource_servicesScalarFieldEnum[]
}

/**
 * salon_services without action
 */
export type salon_servicesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the salon_services
   */
  select?: Prisma.salon_servicesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the salon_services
   */
  omit?: Prisma.salon_servicesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.salon_servicesInclude<ExtArgs> | null
}
