
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `schedule_overrides` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model schedule_overrides
 * 
 */
export type schedule_overridesModel = runtime.Types.Result.DefaultSelection<Prisma.$schedule_overridesPayload>

export type AggregateSchedule_overrides = {
  _count: Schedule_overridesCountAggregateOutputType | null
  _avg: Schedule_overridesAvgAggregateOutputType | null
  _sum: Schedule_overridesSumAggregateOutputType | null
  _min: Schedule_overridesMinAggregateOutputType | null
  _max: Schedule_overridesMaxAggregateOutputType | null
}

export type Schedule_overridesAvgAggregateOutputType = {
  id: number | null
  resource_id: number | null
}

export type Schedule_overridesSumAggregateOutputType = {
  id: number | null
  resource_id: number | null
}

export type Schedule_overridesMinAggregateOutputType = {
  id: number | null
  resource_id: number | null
  date: Date | null
  working: boolean | null
  start_time: Date | null
  end_time: Date | null
  note: string | null
}

export type Schedule_overridesMaxAggregateOutputType = {
  id: number | null
  resource_id: number | null
  date: Date | null
  working: boolean | null
  start_time: Date | null
  end_time: Date | null
  note: string | null
}

export type Schedule_overridesCountAggregateOutputType = {
  id: number
  resource_id: number
  date: number
  working: number
  start_time: number
  end_time: number
  note: number
  _all: number
}


export type Schedule_overridesAvgAggregateInputType = {
  id?: true
  resource_id?: true
}

export type Schedule_overridesSumAggregateInputType = {
  id?: true
  resource_id?: true
}

export type Schedule_overridesMinAggregateInputType = {
  id?: true
  resource_id?: true
  date?: true
  working?: true
  start_time?: true
  end_time?: true
  note?: true
}

export type Schedule_overridesMaxAggregateInputType = {
  id?: true
  resource_id?: true
  date?: true
  working?: true
  start_time?: true
  end_time?: true
  note?: true
}

export type Schedule_overridesCountAggregateInputType = {
  id?: true
  resource_id?: true
  date?: true
  working?: true
  start_time?: true
  end_time?: true
  note?: true
  _all?: true
}

export type Schedule_overridesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which schedule_overrides to aggregate.
   */
  where?: Prisma.schedule_overridesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of schedule_overrides to fetch.
   */
  orderBy?: Prisma.schedule_overridesOrderByWithRelationInput | Prisma.schedule_overridesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.schedule_overridesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` schedule_overrides from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` schedule_overrides.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned schedule_overrides
  **/
  _count?: true | Schedule_overridesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Schedule_overridesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Schedule_overridesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Schedule_overridesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Schedule_overridesMaxAggregateInputType
}

export type GetSchedule_overridesAggregateType<T extends Schedule_overridesAggregateArgs> = {
      [P in keyof T & keyof AggregateSchedule_overrides]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSchedule_overrides[P]>
    : Prisma.GetScalarType<T[P], AggregateSchedule_overrides[P]>
}




export type schedule_overridesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.schedule_overridesWhereInput
  orderBy?: Prisma.schedule_overridesOrderByWithAggregationInput | Prisma.schedule_overridesOrderByWithAggregationInput[]
  by: Prisma.Schedule_overridesScalarFieldEnum[] | Prisma.Schedule_overridesScalarFieldEnum
  having?: Prisma.schedule_overridesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Schedule_overridesCountAggregateInputType | true
  _avg?: Schedule_overridesAvgAggregateInputType
  _sum?: Schedule_overridesSumAggregateInputType
  _min?: Schedule_overridesMinAggregateInputType
  _max?: Schedule_overridesMaxAggregateInputType
}

export type Schedule_overridesGroupByOutputType = {
  id: number
  resource_id: number
  date: Date
  working: boolean
  start_time: Date | null
  end_time: Date | null
  note: string | null
  _count: Schedule_overridesCountAggregateOutputType | null
  _avg: Schedule_overridesAvgAggregateOutputType | null
  _sum: Schedule_overridesSumAggregateOutputType | null
  _min: Schedule_overridesMinAggregateOutputType | null
  _max: Schedule_overridesMaxAggregateOutputType | null
}

type GetSchedule_overridesGroupByPayload<T extends schedule_overridesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Schedule_overridesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Schedule_overridesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Schedule_overridesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Schedule_overridesGroupByOutputType[P]>
      }
    >
  >



export type schedule_overridesWhereInput = {
  AND?: Prisma.schedule_overridesWhereInput | Prisma.schedule_overridesWhereInput[]
  OR?: Prisma.schedule_overridesWhereInput[]
  NOT?: Prisma.schedule_overridesWhereInput | Prisma.schedule_overridesWhereInput[]
  id?: Prisma.IntFilter<"schedule_overrides"> | number
  resource_id?: Prisma.IntFilter<"schedule_overrides"> | number
  date?: Prisma.DateTimeFilter<"schedule_overrides"> | Date | string
  working?: Prisma.BoolFilter<"schedule_overrides"> | boolean
  start_time?: Prisma.DateTimeNullableFilter<"schedule_overrides"> | Date | string | null
  end_time?: Prisma.DateTimeNullableFilter<"schedule_overrides"> | Date | string | null
  note?: Prisma.StringNullableFilter<"schedule_overrides"> | string | null
  resources?: Prisma.XOR<Prisma.ResourcesScalarRelationFilter, Prisma.resourcesWhereInput>
}

export type schedule_overridesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  working?: Prisma.SortOrder
  start_time?: Prisma.SortOrderInput | Prisma.SortOrder
  end_time?: Prisma.SortOrderInput | Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  resources?: Prisma.resourcesOrderByWithRelationInput
}

export type schedule_overridesWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  resource_id_date?: Prisma.schedule_overridesResource_idDateCompoundUniqueInput
  AND?: Prisma.schedule_overridesWhereInput | Prisma.schedule_overridesWhereInput[]
  OR?: Prisma.schedule_overridesWhereInput[]
  NOT?: Prisma.schedule_overridesWhereInput | Prisma.schedule_overridesWhereInput[]
  resource_id?: Prisma.IntFilter<"schedule_overrides"> | number
  date?: Prisma.DateTimeFilter<"schedule_overrides"> | Date | string
  working?: Prisma.BoolFilter<"schedule_overrides"> | boolean
  start_time?: Prisma.DateTimeNullableFilter<"schedule_overrides"> | Date | string | null
  end_time?: Prisma.DateTimeNullableFilter<"schedule_overrides"> | Date | string | null
  note?: Prisma.StringNullableFilter<"schedule_overrides"> | string | null
  resources?: Prisma.XOR<Prisma.ResourcesScalarRelationFilter, Prisma.resourcesWhereInput>
}, "id" | "resource_id_date">

export type schedule_overridesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  working?: Prisma.SortOrder
  start_time?: Prisma.SortOrderInput | Prisma.SortOrder
  end_time?: Prisma.SortOrderInput | Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.schedule_overridesCountOrderByAggregateInput
  _avg?: Prisma.schedule_overridesAvgOrderByAggregateInput
  _max?: Prisma.schedule_overridesMaxOrderByAggregateInput
  _min?: Prisma.schedule_overridesMinOrderByAggregateInput
  _sum?: Prisma.schedule_overridesSumOrderByAggregateInput
}

export type schedule_overridesScalarWhereWithAggregatesInput = {
  AND?: Prisma.schedule_overridesScalarWhereWithAggregatesInput | Prisma.schedule_overridesScalarWhereWithAggregatesInput[]
  OR?: Prisma.schedule_overridesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.schedule_overridesScalarWhereWithAggregatesInput | Prisma.schedule_overridesScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"schedule_overrides"> | number
  resource_id?: Prisma.IntWithAggregatesFilter<"schedule_overrides"> | number
  date?: Prisma.DateTimeWithAggregatesFilter<"schedule_overrides"> | Date | string
  working?: Prisma.BoolWithAggregatesFilter<"schedule_overrides"> | boolean
  start_time?: Prisma.DateTimeNullableWithAggregatesFilter<"schedule_overrides"> | Date | string | null
  end_time?: Prisma.DateTimeNullableWithAggregatesFilter<"schedule_overrides"> | Date | string | null
  note?: Prisma.StringNullableWithAggregatesFilter<"schedule_overrides"> | string | null
}

export type schedule_overridesCreateInput = {
  date: Date | string
  working?: boolean
  start_time?: Date | string | null
  end_time?: Date | string | null
  note?: string | null
  resources: Prisma.resourcesCreateNestedOneWithoutSchedule_overridesInput
}

export type schedule_overridesUncheckedCreateInput = {
  id?: number
  resource_id: number
  date: Date | string
  working?: boolean
  start_time?: Date | string | null
  end_time?: Date | string | null
  note?: string | null
}

export type schedule_overridesUpdateInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  working?: Prisma.BoolFieldUpdateOperationsInput | boolean
  start_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  resources?: Prisma.resourcesUpdateOneRequiredWithoutSchedule_overridesNestedInput
}

export type schedule_overridesUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resource_id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  working?: Prisma.BoolFieldUpdateOperationsInput | boolean
  start_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type schedule_overridesCreateManyInput = {
  id?: number
  resource_id: number
  date: Date | string
  working?: boolean
  start_time?: Date | string | null
  end_time?: Date | string | null
  note?: string | null
}

export type schedule_overridesUpdateManyMutationInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  working?: Prisma.BoolFieldUpdateOperationsInput | boolean
  start_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type schedule_overridesUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resource_id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  working?: Prisma.BoolFieldUpdateOperationsInput | boolean
  start_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type Schedule_overridesListRelationFilter = {
  every?: Prisma.schedule_overridesWhereInput
  some?: Prisma.schedule_overridesWhereInput
  none?: Prisma.schedule_overridesWhereInput
}

export type schedule_overridesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type schedule_overridesResource_idDateCompoundUniqueInput = {
  resource_id: number
  date: Date | string
}

export type schedule_overridesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  working?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  note?: Prisma.SortOrder
}

export type schedule_overridesAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
}

export type schedule_overridesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  working?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  note?: Prisma.SortOrder
}

export type schedule_overridesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  working?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  note?: Prisma.SortOrder
}

export type schedule_overridesSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
}

export type schedule_overridesCreateNestedManyWithoutResourcesInput = {
  create?: Prisma.XOR<Prisma.schedule_overridesCreateWithoutResourcesInput, Prisma.schedule_overridesUncheckedCreateWithoutResourcesInput> | Prisma.schedule_overridesCreateWithoutResourcesInput[] | Prisma.schedule_overridesUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.schedule_overridesCreateOrConnectWithoutResourcesInput | Prisma.schedule_overridesCreateOrConnectWithoutResourcesInput[]
  createMany?: Prisma.schedule_overridesCreateManyResourcesInputEnvelope
  connect?: Prisma.schedule_overridesWhereUniqueInput | Prisma.schedule_overridesWhereUniqueInput[]
}

export type schedule_overridesUncheckedCreateNestedManyWithoutResourcesInput = {
  create?: Prisma.XOR<Prisma.schedule_overridesCreateWithoutResourcesInput, Prisma.schedule_overridesUncheckedCreateWithoutResourcesInput> | Prisma.schedule_overridesCreateWithoutResourcesInput[] | Prisma.schedule_overridesUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.schedule_overridesCreateOrConnectWithoutResourcesInput | Prisma.schedule_overridesCreateOrConnectWithoutResourcesInput[]
  createMany?: Prisma.schedule_overridesCreateManyResourcesInputEnvelope
  connect?: Prisma.schedule_overridesWhereUniqueInput | Prisma.schedule_overridesWhereUniqueInput[]
}

export type schedule_overridesUpdateManyWithoutResourcesNestedInput = {
  create?: Prisma.XOR<Prisma.schedule_overridesCreateWithoutResourcesInput, Prisma.schedule_overridesUncheckedCreateWithoutResourcesInput> | Prisma.schedule_overridesCreateWithoutResourcesInput[] | Prisma.schedule_overridesUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.schedule_overridesCreateOrConnectWithoutResourcesInput | Prisma.schedule_overridesCreateOrConnectWithoutResourcesInput[]
  upsert?: Prisma.schedule_overridesUpsertWithWhereUniqueWithoutResourcesInput | Prisma.schedule_overridesUpsertWithWhereUniqueWithoutResourcesInput[]
  createMany?: Prisma.schedule_overridesCreateManyResourcesInputEnvelope
  set?: Prisma.schedule_overridesWhereUniqueInput | Prisma.schedule_overridesWhereUniqueInput[]
  disconnect?: Prisma.schedule_overridesWhereUniqueInput | Prisma.schedule_overridesWhereUniqueInput[]
  delete?: Prisma.schedule_overridesWhereUniqueInput | Prisma.schedule_overridesWhereUniqueInput[]
  connect?: Prisma.schedule_overridesWhereUniqueInput | Prisma.schedule_overridesWhereUniqueInput[]
  update?: Prisma.schedule_overridesUpdateWithWhereUniqueWithoutResourcesInput | Prisma.schedule_overridesUpdateWithWhereUniqueWithoutResourcesInput[]
  updateMany?: Prisma.schedule_overridesUpdateManyWithWhereWithoutResourcesInput | Prisma.schedule_overridesUpdateManyWithWhereWithoutResourcesInput[]
  deleteMany?: Prisma.schedule_overridesScalarWhereInput | Prisma.schedule_overridesScalarWhereInput[]
}

export type schedule_overridesUncheckedUpdateManyWithoutResourcesNestedInput = {
  create?: Prisma.XOR<Prisma.schedule_overridesCreateWithoutResourcesInput, Prisma.schedule_overridesUncheckedCreateWithoutResourcesInput> | Prisma.schedule_overridesCreateWithoutResourcesInput[] | Prisma.schedule_overridesUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.schedule_overridesCreateOrConnectWithoutResourcesInput | Prisma.schedule_overridesCreateOrConnectWithoutResourcesInput[]
  upsert?: Prisma.schedule_overridesUpsertWithWhereUniqueWithoutResourcesInput | Prisma.schedule_overridesUpsertWithWhereUniqueWithoutResourcesInput[]
  createMany?: Prisma.schedule_overridesCreateManyResourcesInputEnvelope
  set?: Prisma.schedule_overridesWhereUniqueInput | Prisma.schedule_overridesWhereUniqueInput[]
  disconnect?: Prisma.schedule_overridesWhereUniqueInput | Prisma.schedule_overridesWhereUniqueInput[]
  delete?: Prisma.schedule_overridesWhereUniqueInput | Prisma.schedule_overridesWhereUniqueInput[]
  connect?: Prisma.schedule_overridesWhereUniqueInput | Prisma.schedule_overridesWhereUniqueInput[]
  update?: Prisma.schedule_overridesUpdateWithWhereUniqueWithoutResourcesInput | Prisma.schedule_overridesUpdateWithWhereUniqueWithoutResourcesInput[]
  updateMany?: Prisma.schedule_overridesUpdateManyWithWhereWithoutResourcesInput | Prisma.schedule_overridesUpdateManyWithWhereWithoutResourcesInput[]
  deleteMany?: Prisma.schedule_overridesScalarWhereInput | Prisma.schedule_overridesScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type schedule_overridesCreateWithoutResourcesInput = {
  date: Date | string
  working?: boolean
  start_time?: Date | string | null
  end_time?: Date | string | null
  note?: string | null
}

export type schedule_overridesUncheckedCreateWithoutResourcesInput = {
  id?: number
  date: Date | string
  working?: boolean
  start_time?: Date | string | null
  end_time?: Date | string | null
  note?: string | null
}

export type schedule_overridesCreateOrConnectWithoutResourcesInput = {
  where: Prisma.schedule_overridesWhereUniqueInput
  create: Prisma.XOR<Prisma.schedule_overridesCreateWithoutResourcesInput, Prisma.schedule_overridesUncheckedCreateWithoutResourcesInput>
}

export type schedule_overridesCreateManyResourcesInputEnvelope = {
  data: Prisma.schedule_overridesCreateManyResourcesInput | Prisma.schedule_overridesCreateManyResourcesInput[]
  skipDuplicates?: boolean
}

export type schedule_overridesUpsertWithWhereUniqueWithoutResourcesInput = {
  where: Prisma.schedule_overridesWhereUniqueInput
  update: Prisma.XOR<Prisma.schedule_overridesUpdateWithoutResourcesInput, Prisma.schedule_overridesUncheckedUpdateWithoutResourcesInput>
  create: Prisma.XOR<Prisma.schedule_overridesCreateWithoutResourcesInput, Prisma.schedule_overridesUncheckedCreateWithoutResourcesInput>
}

export type schedule_overridesUpdateWithWhereUniqueWithoutResourcesInput = {
  where: Prisma.schedule_overridesWhereUniqueInput
  data: Prisma.XOR<Prisma.schedule_overridesUpdateWithoutResourcesInput, Prisma.schedule_overridesUncheckedUpdateWithoutResourcesInput>
}

export type schedule_overridesUpdateManyWithWhereWithoutResourcesInput = {
  where: Prisma.schedule_overridesScalarWhereInput
  data: Prisma.XOR<Prisma.schedule_overridesUpdateManyMutationInput, Prisma.schedule_overridesUncheckedUpdateManyWithoutResourcesInput>
}

export type schedule_overridesScalarWhereInput = {
  AND?: Prisma.schedule_overridesScalarWhereInput | Prisma.schedule_overridesScalarWhereInput[]
  OR?: Prisma.schedule_overridesScalarWhereInput[]
  NOT?: Prisma.schedule_overridesScalarWhereInput | Prisma.schedule_overridesScalarWhereInput[]
  id?: Prisma.IntFilter<"schedule_overrides"> | number
  resource_id?: Prisma.IntFilter<"schedule_overrides"> | number
  date?: Prisma.DateTimeFilter<"schedule_overrides"> | Date | string
  working?: Prisma.BoolFilter<"schedule_overrides"> | boolean
  start_time?: Prisma.DateTimeNullableFilter<"schedule_overrides"> | Date | string | null
  end_time?: Prisma.DateTimeNullableFilter<"schedule_overrides"> | Date | string | null
  note?: Prisma.StringNullableFilter<"schedule_overrides"> | string | null
}

export type schedule_overridesCreateManyResourcesInput = {
  id?: number
  date: Date | string
  working?: boolean
  start_time?: Date | string | null
  end_time?: Date | string | null
  note?: string | null
}

export type schedule_overridesUpdateWithoutResourcesInput = {
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  working?: Prisma.BoolFieldUpdateOperationsInput | boolean
  start_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type schedule_overridesUncheckedUpdateWithoutResourcesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  working?: Prisma.BoolFieldUpdateOperationsInput | boolean
  start_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type schedule_overridesUncheckedUpdateManyWithoutResourcesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  working?: Prisma.BoolFieldUpdateOperationsInput | boolean
  start_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type schedule_overridesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  resource_id?: boolean
  date?: boolean
  working?: boolean
  start_time?: boolean
  end_time?: boolean
  note?: boolean
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["schedule_overrides"]>

export type schedule_overridesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  resource_id?: boolean
  date?: boolean
  working?: boolean
  start_time?: boolean
  end_time?: boolean
  note?: boolean
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["schedule_overrides"]>

export type schedule_overridesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  resource_id?: boolean
  date?: boolean
  working?: boolean
  start_time?: boolean
  end_time?: boolean
  note?: boolean
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["schedule_overrides"]>

export type schedule_overridesSelectScalar = {
  id?: boolean
  resource_id?: boolean
  date?: boolean
  working?: boolean
  start_time?: boolean
  end_time?: boolean
  note?: boolean
}

export type schedule_overridesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "resource_id" | "date" | "working" | "start_time" | "end_time" | "note", ExtArgs["result"]["schedule_overrides"]>
export type schedule_overridesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
}
export type schedule_overridesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
}
export type schedule_overridesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
}

export type $schedule_overridesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "schedule_overrides"
  objects: {
    resources: Prisma.$resourcesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    resource_id: number
    date: Date
    working: boolean
    start_time: Date | null
    end_time: Date | null
    note: string | null
  }, ExtArgs["result"]["schedule_overrides"]>
  composites: {}
}

export type schedule_overridesGetPayload<S extends boolean | null | undefined | schedule_overridesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$schedule_overridesPayload, S>

export type schedule_overridesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<schedule_overridesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Schedule_overridesCountAggregateInputType | true
  }

export interface schedule_overridesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['schedule_overrides'], meta: { name: 'schedule_overrides' } }
  /**
   * Find zero or one Schedule_overrides that matches the filter.
   * @param {schedule_overridesFindUniqueArgs} args - Arguments to find a Schedule_overrides
   * @example
   * // Get one Schedule_overrides
   * const schedule_overrides = await prisma.schedule_overrides.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends schedule_overridesFindUniqueArgs>(args: Prisma.SelectSubset<T, schedule_overridesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__schedule_overridesClient<runtime.Types.Result.GetResult<Prisma.$schedule_overridesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Schedule_overrides that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {schedule_overridesFindUniqueOrThrowArgs} args - Arguments to find a Schedule_overrides
   * @example
   * // Get one Schedule_overrides
   * const schedule_overrides = await prisma.schedule_overrides.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends schedule_overridesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, schedule_overridesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__schedule_overridesClient<runtime.Types.Result.GetResult<Prisma.$schedule_overridesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Schedule_overrides that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {schedule_overridesFindFirstArgs} args - Arguments to find a Schedule_overrides
   * @example
   * // Get one Schedule_overrides
   * const schedule_overrides = await prisma.schedule_overrides.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends schedule_overridesFindFirstArgs>(args?: Prisma.SelectSubset<T, schedule_overridesFindFirstArgs<ExtArgs>>): Prisma.Prisma__schedule_overridesClient<runtime.Types.Result.GetResult<Prisma.$schedule_overridesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Schedule_overrides that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {schedule_overridesFindFirstOrThrowArgs} args - Arguments to find a Schedule_overrides
   * @example
   * // Get one Schedule_overrides
   * const schedule_overrides = await prisma.schedule_overrides.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends schedule_overridesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, schedule_overridesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__schedule_overridesClient<runtime.Types.Result.GetResult<Prisma.$schedule_overridesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Schedule_overrides that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {schedule_overridesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Schedule_overrides
   * const schedule_overrides = await prisma.schedule_overrides.findMany()
   * 
   * // Get first 10 Schedule_overrides
   * const schedule_overrides = await prisma.schedule_overrides.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const schedule_overridesWithIdOnly = await prisma.schedule_overrides.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends schedule_overridesFindManyArgs>(args?: Prisma.SelectSubset<T, schedule_overridesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$schedule_overridesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Schedule_overrides.
   * @param {schedule_overridesCreateArgs} args - Arguments to create a Schedule_overrides.
   * @example
   * // Create one Schedule_overrides
   * const Schedule_overrides = await prisma.schedule_overrides.create({
   *   data: {
   *     // ... data to create a Schedule_overrides
   *   }
   * })
   * 
   */
  create<T extends schedule_overridesCreateArgs>(args: Prisma.SelectSubset<T, schedule_overridesCreateArgs<ExtArgs>>): Prisma.Prisma__schedule_overridesClient<runtime.Types.Result.GetResult<Prisma.$schedule_overridesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Schedule_overrides.
   * @param {schedule_overridesCreateManyArgs} args - Arguments to create many Schedule_overrides.
   * @example
   * // Create many Schedule_overrides
   * const schedule_overrides = await prisma.schedule_overrides.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends schedule_overridesCreateManyArgs>(args?: Prisma.SelectSubset<T, schedule_overridesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Schedule_overrides and returns the data saved in the database.
   * @param {schedule_overridesCreateManyAndReturnArgs} args - Arguments to create many Schedule_overrides.
   * @example
   * // Create many Schedule_overrides
   * const schedule_overrides = await prisma.schedule_overrides.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Schedule_overrides and only return the `id`
   * const schedule_overridesWithIdOnly = await prisma.schedule_overrides.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends schedule_overridesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, schedule_overridesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$schedule_overridesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Schedule_overrides.
   * @param {schedule_overridesDeleteArgs} args - Arguments to delete one Schedule_overrides.
   * @example
   * // Delete one Schedule_overrides
   * const Schedule_overrides = await prisma.schedule_overrides.delete({
   *   where: {
   *     // ... filter to delete one Schedule_overrides
   *   }
   * })
   * 
   */
  delete<T extends schedule_overridesDeleteArgs>(args: Prisma.SelectSubset<T, schedule_overridesDeleteArgs<ExtArgs>>): Prisma.Prisma__schedule_overridesClient<runtime.Types.Result.GetResult<Prisma.$schedule_overridesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Schedule_overrides.
   * @param {schedule_overridesUpdateArgs} args - Arguments to update one Schedule_overrides.
   * @example
   * // Update one Schedule_overrides
   * const schedule_overrides = await prisma.schedule_overrides.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends schedule_overridesUpdateArgs>(args: Prisma.SelectSubset<T, schedule_overridesUpdateArgs<ExtArgs>>): Prisma.Prisma__schedule_overridesClient<runtime.Types.Result.GetResult<Prisma.$schedule_overridesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Schedule_overrides.
   * @param {schedule_overridesDeleteManyArgs} args - Arguments to filter Schedule_overrides to delete.
   * @example
   * // Delete a few Schedule_overrides
   * const { count } = await prisma.schedule_overrides.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends schedule_overridesDeleteManyArgs>(args?: Prisma.SelectSubset<T, schedule_overridesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Schedule_overrides.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {schedule_overridesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Schedule_overrides
   * const schedule_overrides = await prisma.schedule_overrides.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends schedule_overridesUpdateManyArgs>(args: Prisma.SelectSubset<T, schedule_overridesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Schedule_overrides and returns the data updated in the database.
   * @param {schedule_overridesUpdateManyAndReturnArgs} args - Arguments to update many Schedule_overrides.
   * @example
   * // Update many Schedule_overrides
   * const schedule_overrides = await prisma.schedule_overrides.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Schedule_overrides and only return the `id`
   * const schedule_overridesWithIdOnly = await prisma.schedule_overrides.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends schedule_overridesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, schedule_overridesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$schedule_overridesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Schedule_overrides.
   * @param {schedule_overridesUpsertArgs} args - Arguments to update or create a Schedule_overrides.
   * @example
   * // Update or create a Schedule_overrides
   * const schedule_overrides = await prisma.schedule_overrides.upsert({
   *   create: {
   *     // ... data to create a Schedule_overrides
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Schedule_overrides we want to update
   *   }
   * })
   */
  upsert<T extends schedule_overridesUpsertArgs>(args: Prisma.SelectSubset<T, schedule_overridesUpsertArgs<ExtArgs>>): Prisma.Prisma__schedule_overridesClient<runtime.Types.Result.GetResult<Prisma.$schedule_overridesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Schedule_overrides.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {schedule_overridesCountArgs} args - Arguments to filter Schedule_overrides to count.
   * @example
   * // Count the number of Schedule_overrides
   * const count = await prisma.schedule_overrides.count({
   *   where: {
   *     // ... the filter for the Schedule_overrides we want to count
   *   }
   * })
  **/
  count<T extends schedule_overridesCountArgs>(
    args?: Prisma.Subset<T, schedule_overridesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Schedule_overridesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Schedule_overrides.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Schedule_overridesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Schedule_overridesAggregateArgs>(args: Prisma.Subset<T, Schedule_overridesAggregateArgs>): Prisma.PrismaPromise<GetSchedule_overridesAggregateType<T>>

  /**
   * Group by Schedule_overrides.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {schedule_overridesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends schedule_overridesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: schedule_overridesGroupByArgs['orderBy'] }
      : { orderBy?: schedule_overridesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, schedule_overridesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSchedule_overridesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the schedule_overrides model
 */
readonly fields: schedule_overridesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for schedule_overrides.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__schedule_overridesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  resources<T extends Prisma.resourcesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.resourcesDefaultArgs<ExtArgs>>): Prisma.Prisma__resourcesClient<runtime.Types.Result.GetResult<Prisma.$resourcesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the schedule_overrides model
 */
export interface schedule_overridesFieldRefs {
  readonly id: Prisma.FieldRef<"schedule_overrides", 'Int'>
  readonly resource_id: Prisma.FieldRef<"schedule_overrides", 'Int'>
  readonly date: Prisma.FieldRef<"schedule_overrides", 'DateTime'>
  readonly working: Prisma.FieldRef<"schedule_overrides", 'Boolean'>
  readonly start_time: Prisma.FieldRef<"schedule_overrides", 'DateTime'>
  readonly end_time: Prisma.FieldRef<"schedule_overrides", 'DateTime'>
  readonly note: Prisma.FieldRef<"schedule_overrides", 'String'>
}
    

// Custom InputTypes
/**
 * schedule_overrides findUnique
 */
export type schedule_overridesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the schedule_overrides
   */
  select?: Prisma.schedule_overridesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the schedule_overrides
   */
  omit?: Prisma.schedule_overridesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.schedule_overridesInclude<ExtArgs> | null
  /**
   * Filter, which schedule_overrides to fetch.
   */
  where: Prisma.schedule_overridesWhereUniqueInput
}

/**
 * schedule_overrides findUniqueOrThrow
 */
export type schedule_overridesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the schedule_overrides
   */
  select?: Prisma.schedule_overridesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the schedule_overrides
   */
  omit?: Prisma.schedule_overridesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.schedule_overridesInclude<ExtArgs> | null
  /**
   * Filter, which schedule_overrides to fetch.
   */
  where: Prisma.schedule_overridesWhereUniqueInput
}

/**
 * schedule_overrides findFirst
 */
export type schedule_overridesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the schedule_overrides
   */
  select?: Prisma.schedule_overridesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the schedule_overrides
   */
  omit?: Prisma.schedule_overridesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.schedule_overridesInclude<ExtArgs> | null
  /**
   * Filter, which schedule_overrides to fetch.
   */
  where?: Prisma.schedule_overridesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of schedule_overrides to fetch.
   */
  orderBy?: Prisma.schedule_overridesOrderByWithRelationInput | Prisma.schedule_overridesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for schedule_overrides.
   */
  cursor?: Prisma.schedule_overridesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` schedule_overrides from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` schedule_overrides.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of schedule_overrides.
   */
  distinct?: Prisma.Schedule_overridesScalarFieldEnum | Prisma.Schedule_overridesScalarFieldEnum[]
}

/**
 * schedule_overrides findFirstOrThrow
 */
export type schedule_overridesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the schedule_overrides
   */
  select?: Prisma.schedule_overridesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the schedule_overrides
   */
  omit?: Prisma.schedule_overridesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.schedule_overridesInclude<ExtArgs> | null
  /**
   * Filter, which schedule_overrides to fetch.
   */
  where?: Prisma.schedule_overridesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of schedule_overrides to fetch.
   */
  orderBy?: Prisma.schedule_overridesOrderByWithRelationInput | Prisma.schedule_overridesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for schedule_overrides.
   */
  cursor?: Prisma.schedule_overridesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` schedule_overrides from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` schedule_overrides.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of schedule_overrides.
   */
  distinct?: Prisma.Schedule_overridesScalarFieldEnum | Prisma.Schedule_overridesScalarFieldEnum[]
}

/**
 * schedule_overrides findMany
 */
export type schedule_overridesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the schedule_overrides
   */
  select?: Prisma.schedule_overridesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the schedule_overrides
   */
  omit?: Prisma.schedule_overridesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.schedule_overridesInclude<ExtArgs> | null
  /**
   * Filter, which schedule_overrides to fetch.
   */
  where?: Prisma.schedule_overridesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of schedule_overrides to fetch.
   */
  orderBy?: Prisma.schedule_overridesOrderByWithRelationInput | Prisma.schedule_overridesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing schedule_overrides.
   */
  cursor?: Prisma.schedule_overridesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` schedule_overrides from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` schedule_overrides.
   */
  skip?: number
  distinct?: Prisma.Schedule_overridesScalarFieldEnum | Prisma.Schedule_overridesScalarFieldEnum[]
}

/**
 * schedule_overrides create
 */
export type schedule_overridesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the schedule_overrides
   */
  select?: Prisma.schedule_overridesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the schedule_overrides
   */
  omit?: Prisma.schedule_overridesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.schedule_overridesInclude<ExtArgs> | null
  /**
   * The data needed to create a schedule_overrides.
   */
  data: Prisma.XOR<Prisma.schedule_overridesCreateInput, Prisma.schedule_overridesUncheckedCreateInput>
}

/**
 * schedule_overrides createMany
 */
export type schedule_overridesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many schedule_overrides.
   */
  data: Prisma.schedule_overridesCreateManyInput | Prisma.schedule_overridesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * schedule_overrides createManyAndReturn
 */
export type schedule_overridesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the schedule_overrides
   */
  select?: Prisma.schedule_overridesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the schedule_overrides
   */
  omit?: Prisma.schedule_overridesOmit<ExtArgs> | null
  /**
   * The data used to create many schedule_overrides.
   */
  data: Prisma.schedule_overridesCreateManyInput | Prisma.schedule_overridesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.schedule_overridesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * schedule_overrides update
 */
export type schedule_overridesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the schedule_overrides
   */
  select?: Prisma.schedule_overridesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the schedule_overrides
   */
  omit?: Prisma.schedule_overridesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.schedule_overridesInclude<ExtArgs> | null
  /**
   * The data needed to update a schedule_overrides.
   */
  data: Prisma.XOR<Prisma.schedule_overridesUpdateInput, Prisma.schedule_overridesUncheckedUpdateInput>
  /**
   * Choose, which schedule_overrides to update.
   */
  where: Prisma.schedule_overridesWhereUniqueInput
}

/**
 * schedule_overrides updateMany
 */
export type schedule_overridesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update schedule_overrides.
   */
  data: Prisma.XOR<Prisma.schedule_overridesUpdateManyMutationInput, Prisma.schedule_overridesUncheckedUpdateManyInput>
  /**
   * Filter which schedule_overrides to update
   */
  where?: Prisma.schedule_overridesWhereInput
  /**
   * Limit how many schedule_overrides to update.
   */
  limit?: number
}

/**
 * schedule_overrides updateManyAndReturn
 */
export type schedule_overridesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the schedule_overrides
   */
  select?: Prisma.schedule_overridesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the schedule_overrides
   */
  omit?: Prisma.schedule_overridesOmit<ExtArgs> | null
  /**
   * The data used to update schedule_overrides.
   */
  data: Prisma.XOR<Prisma.schedule_overridesUpdateManyMutationInput, Prisma.schedule_overridesUncheckedUpdateManyInput>
  /**
   * Filter which schedule_overrides to update
   */
  where?: Prisma.schedule_overridesWhereInput
  /**
   * Limit how many schedule_overrides to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.schedule_overridesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * schedule_overrides upsert
 */
export type schedule_overridesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the schedule_overrides
   */
  select?: Prisma.schedule_overridesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the schedule_overrides
   */
  omit?: Prisma.schedule_overridesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.schedule_overridesInclude<ExtArgs> | null
  /**
   * The filter to search for the schedule_overrides to update in case it exists.
   */
  where: Prisma.schedule_overridesWhereUniqueInput
  /**
   * In case the schedule_overrides found by the `where` argument doesn't exist, create a new schedule_overrides with this data.
   */
  create: Prisma.XOR<Prisma.schedule_overridesCreateInput, Prisma.schedule_overridesUncheckedCreateInput>
  /**
   * In case the schedule_overrides was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.schedule_overridesUpdateInput, Prisma.schedule_overridesUncheckedUpdateInput>
}

/**
 * schedule_overrides delete
 */
export type schedule_overridesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the schedule_overrides
   */
  select?: Prisma.schedule_overridesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the schedule_overrides
   */
  omit?: Prisma.schedule_overridesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.schedule_overridesInclude<ExtArgs> | null
  /**
   * Filter which schedule_overrides to delete.
   */
  where: Prisma.schedule_overridesWhereUniqueInput
}

/**
 * schedule_overrides deleteMany
 */
export type schedule_overridesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which schedule_overrides to delete
   */
  where?: Prisma.schedule_overridesWhereInput
  /**
   * Limit how many schedule_overrides to delete.
   */
  limit?: number
}

/**
 * schedule_overrides without action
 */
export type schedule_overridesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the schedule_overrides
   */
  select?: Prisma.schedule_overridesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the schedule_overrides
   */
  omit?: Prisma.schedule_overridesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.schedule_overridesInclude<ExtArgs> | null
}
