
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `working_hours` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model working_hours
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type working_hoursModel = runtime.Types.Result.DefaultSelection<Prisma.$working_hoursPayload>

export type AggregateWorking_hours = {
  _count: Working_hoursCountAggregateOutputType | null
  _avg: Working_hoursAvgAggregateOutputType | null
  _sum: Working_hoursSumAggregateOutputType | null
  _min: Working_hoursMinAggregateOutputType | null
  _max: Working_hoursMaxAggregateOutputType | null
}

export type Working_hoursAvgAggregateOutputType = {
  id: number | null
  resource_id: number | null
  weekday: number | null
}

export type Working_hoursSumAggregateOutputType = {
  id: number | null
  resource_id: number | null
  weekday: number | null
}

export type Working_hoursMinAggregateOutputType = {
  id: number | null
  resource_id: number | null
  weekday: number | null
  start_time: Date | null
  end_time: Date | null
}

export type Working_hoursMaxAggregateOutputType = {
  id: number | null
  resource_id: number | null
  weekday: number | null
  start_time: Date | null
  end_time: Date | null
}

export type Working_hoursCountAggregateOutputType = {
  id: number
  resource_id: number
  weekday: number
  start_time: number
  end_time: number
  _all: number
}


export type Working_hoursAvgAggregateInputType = {
  id?: true
  resource_id?: true
  weekday?: true
}

export type Working_hoursSumAggregateInputType = {
  id?: true
  resource_id?: true
  weekday?: true
}

export type Working_hoursMinAggregateInputType = {
  id?: true
  resource_id?: true
  weekday?: true
  start_time?: true
  end_time?: true
}

export type Working_hoursMaxAggregateInputType = {
  id?: true
  resource_id?: true
  weekday?: true
  start_time?: true
  end_time?: true
}

export type Working_hoursCountAggregateInputType = {
  id?: true
  resource_id?: true
  weekday?: true
  start_time?: true
  end_time?: true
  _all?: true
}

export type Working_hoursAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which working_hours to aggregate.
   */
  where?: Prisma.working_hoursWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of working_hours to fetch.
   */
  orderBy?: Prisma.working_hoursOrderByWithRelationInput | Prisma.working_hoursOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.working_hoursWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` working_hours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` working_hours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned working_hours
  **/
  _count?: true | Working_hoursCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Working_hoursAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Working_hoursSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Working_hoursMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Working_hoursMaxAggregateInputType
}

export type GetWorking_hoursAggregateType<T extends Working_hoursAggregateArgs> = {
      [P in keyof T & keyof AggregateWorking_hours]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorking_hours[P]>
    : Prisma.GetScalarType<T[P], AggregateWorking_hours[P]>
}




export type working_hoursGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.working_hoursWhereInput
  orderBy?: Prisma.working_hoursOrderByWithAggregationInput | Prisma.working_hoursOrderByWithAggregationInput[]
  by: Prisma.Working_hoursScalarFieldEnum[] | Prisma.Working_hoursScalarFieldEnum
  having?: Prisma.working_hoursScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Working_hoursCountAggregateInputType | true
  _avg?: Working_hoursAvgAggregateInputType
  _sum?: Working_hoursSumAggregateInputType
  _min?: Working_hoursMinAggregateInputType
  _max?: Working_hoursMaxAggregateInputType
}

export type Working_hoursGroupByOutputType = {
  id: number
  resource_id: number
  weekday: number
  start_time: Date
  end_time: Date
  _count: Working_hoursCountAggregateOutputType | null
  _avg: Working_hoursAvgAggregateOutputType | null
  _sum: Working_hoursSumAggregateOutputType | null
  _min: Working_hoursMinAggregateOutputType | null
  _max: Working_hoursMaxAggregateOutputType | null
}

type GetWorking_hoursGroupByPayload<T extends working_hoursGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Working_hoursGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Working_hoursGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Working_hoursGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Working_hoursGroupByOutputType[P]>
      }
    >
  >



export type working_hoursWhereInput = {
  AND?: Prisma.working_hoursWhereInput | Prisma.working_hoursWhereInput[]
  OR?: Prisma.working_hoursWhereInput[]
  NOT?: Prisma.working_hoursWhereInput | Prisma.working_hoursWhereInput[]
  id?: Prisma.IntFilter<"working_hours"> | number
  resource_id?: Prisma.IntFilter<"working_hours"> | number
  weekday?: Prisma.IntFilter<"working_hours"> | number
  start_time?: Prisma.DateTimeFilter<"working_hours"> | Date | string
  end_time?: Prisma.DateTimeFilter<"working_hours"> | Date | string
  resources?: Prisma.XOR<Prisma.ResourcesScalarRelationFilter, Prisma.resourcesWhereInput>
}

export type working_hoursOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  resources?: Prisma.resourcesOrderByWithRelationInput
}

export type working_hoursWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  resource_id_weekday?: Prisma.working_hoursResource_idWeekdayCompoundUniqueInput
  AND?: Prisma.working_hoursWhereInput | Prisma.working_hoursWhereInput[]
  OR?: Prisma.working_hoursWhereInput[]
  NOT?: Prisma.working_hoursWhereInput | Prisma.working_hoursWhereInput[]
  resource_id?: Prisma.IntFilter<"working_hours"> | number
  weekday?: Prisma.IntFilter<"working_hours"> | number
  start_time?: Prisma.DateTimeFilter<"working_hours"> | Date | string
  end_time?: Prisma.DateTimeFilter<"working_hours"> | Date | string
  resources?: Prisma.XOR<Prisma.ResourcesScalarRelationFilter, Prisma.resourcesWhereInput>
}, "id" | "resource_id_weekday">

export type working_hoursOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
  _count?: Prisma.working_hoursCountOrderByAggregateInput
  _avg?: Prisma.working_hoursAvgOrderByAggregateInput
  _max?: Prisma.working_hoursMaxOrderByAggregateInput
  _min?: Prisma.working_hoursMinOrderByAggregateInput
  _sum?: Prisma.working_hoursSumOrderByAggregateInput
}

export type working_hoursScalarWhereWithAggregatesInput = {
  AND?: Prisma.working_hoursScalarWhereWithAggregatesInput | Prisma.working_hoursScalarWhereWithAggregatesInput[]
  OR?: Prisma.working_hoursScalarWhereWithAggregatesInput[]
  NOT?: Prisma.working_hoursScalarWhereWithAggregatesInput | Prisma.working_hoursScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"working_hours"> | number
  resource_id?: Prisma.IntWithAggregatesFilter<"working_hours"> | number
  weekday?: Prisma.IntWithAggregatesFilter<"working_hours"> | number
  start_time?: Prisma.DateTimeWithAggregatesFilter<"working_hours"> | Date | string
  end_time?: Prisma.DateTimeWithAggregatesFilter<"working_hours"> | Date | string
}

export type working_hoursCreateInput = {
  weekday: number
  start_time: Date | string
  end_time: Date | string
  resources: Prisma.resourcesCreateNestedOneWithoutWorking_hoursInput
}

export type working_hoursUncheckedCreateInput = {
  id?: number
  resource_id: number
  weekday: number
  start_time: Date | string
  end_time: Date | string
}

export type working_hoursUpdateInput = {
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  resources?: Prisma.resourcesUpdateOneRequiredWithoutWorking_hoursNestedInput
}

export type working_hoursUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resource_id?: Prisma.IntFieldUpdateOperationsInput | number
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type working_hoursCreateManyInput = {
  id?: number
  resource_id: number
  weekday: number
  start_time: Date | string
  end_time: Date | string
}

export type working_hoursUpdateManyMutationInput = {
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type working_hoursUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  resource_id?: Prisma.IntFieldUpdateOperationsInput | number
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Working_hoursListRelationFilter = {
  every?: Prisma.working_hoursWhereInput
  some?: Prisma.working_hoursWhereInput
  none?: Prisma.working_hoursWhereInput
}

export type working_hoursOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type working_hoursResource_idWeekdayCompoundUniqueInput = {
  resource_id: number
  weekday: number
}

export type working_hoursCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
}

export type working_hoursAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
}

export type working_hoursMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
}

export type working_hoursMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
  start_time?: Prisma.SortOrder
  end_time?: Prisma.SortOrder
}

export type working_hoursSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  resource_id?: Prisma.SortOrder
  weekday?: Prisma.SortOrder
}

export type working_hoursCreateNestedManyWithoutResourcesInput = {
  create?: Prisma.XOR<Prisma.working_hoursCreateWithoutResourcesInput, Prisma.working_hoursUncheckedCreateWithoutResourcesInput> | Prisma.working_hoursCreateWithoutResourcesInput[] | Prisma.working_hoursUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.working_hoursCreateOrConnectWithoutResourcesInput | Prisma.working_hoursCreateOrConnectWithoutResourcesInput[]
  createMany?: Prisma.working_hoursCreateManyResourcesInputEnvelope
  connect?: Prisma.working_hoursWhereUniqueInput | Prisma.working_hoursWhereUniqueInput[]
}

export type working_hoursUncheckedCreateNestedManyWithoutResourcesInput = {
  create?: Prisma.XOR<Prisma.working_hoursCreateWithoutResourcesInput, Prisma.working_hoursUncheckedCreateWithoutResourcesInput> | Prisma.working_hoursCreateWithoutResourcesInput[] | Prisma.working_hoursUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.working_hoursCreateOrConnectWithoutResourcesInput | Prisma.working_hoursCreateOrConnectWithoutResourcesInput[]
  createMany?: Prisma.working_hoursCreateManyResourcesInputEnvelope
  connect?: Prisma.working_hoursWhereUniqueInput | Prisma.working_hoursWhereUniqueInput[]
}

export type working_hoursUpdateManyWithoutResourcesNestedInput = {
  create?: Prisma.XOR<Prisma.working_hoursCreateWithoutResourcesInput, Prisma.working_hoursUncheckedCreateWithoutResourcesInput> | Prisma.working_hoursCreateWithoutResourcesInput[] | Prisma.working_hoursUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.working_hoursCreateOrConnectWithoutResourcesInput | Prisma.working_hoursCreateOrConnectWithoutResourcesInput[]
  upsert?: Prisma.working_hoursUpsertWithWhereUniqueWithoutResourcesInput | Prisma.working_hoursUpsertWithWhereUniqueWithoutResourcesInput[]
  createMany?: Prisma.working_hoursCreateManyResourcesInputEnvelope
  set?: Prisma.working_hoursWhereUniqueInput | Prisma.working_hoursWhereUniqueInput[]
  disconnect?: Prisma.working_hoursWhereUniqueInput | Prisma.working_hoursWhereUniqueInput[]
  delete?: Prisma.working_hoursWhereUniqueInput | Prisma.working_hoursWhereUniqueInput[]
  connect?: Prisma.working_hoursWhereUniqueInput | Prisma.working_hoursWhereUniqueInput[]
  update?: Prisma.working_hoursUpdateWithWhereUniqueWithoutResourcesInput | Prisma.working_hoursUpdateWithWhereUniqueWithoutResourcesInput[]
  updateMany?: Prisma.working_hoursUpdateManyWithWhereWithoutResourcesInput | Prisma.working_hoursUpdateManyWithWhereWithoutResourcesInput[]
  deleteMany?: Prisma.working_hoursScalarWhereInput | Prisma.working_hoursScalarWhereInput[]
}

export type working_hoursUncheckedUpdateManyWithoutResourcesNestedInput = {
  create?: Prisma.XOR<Prisma.working_hoursCreateWithoutResourcesInput, Prisma.working_hoursUncheckedCreateWithoutResourcesInput> | Prisma.working_hoursCreateWithoutResourcesInput[] | Prisma.working_hoursUncheckedCreateWithoutResourcesInput[]
  connectOrCreate?: Prisma.working_hoursCreateOrConnectWithoutResourcesInput | Prisma.working_hoursCreateOrConnectWithoutResourcesInput[]
  upsert?: Prisma.working_hoursUpsertWithWhereUniqueWithoutResourcesInput | Prisma.working_hoursUpsertWithWhereUniqueWithoutResourcesInput[]
  createMany?: Prisma.working_hoursCreateManyResourcesInputEnvelope
  set?: Prisma.working_hoursWhereUniqueInput | Prisma.working_hoursWhereUniqueInput[]
  disconnect?: Prisma.working_hoursWhereUniqueInput | Prisma.working_hoursWhereUniqueInput[]
  delete?: Prisma.working_hoursWhereUniqueInput | Prisma.working_hoursWhereUniqueInput[]
  connect?: Prisma.working_hoursWhereUniqueInput | Prisma.working_hoursWhereUniqueInput[]
  update?: Prisma.working_hoursUpdateWithWhereUniqueWithoutResourcesInput | Prisma.working_hoursUpdateWithWhereUniqueWithoutResourcesInput[]
  updateMany?: Prisma.working_hoursUpdateManyWithWhereWithoutResourcesInput | Prisma.working_hoursUpdateManyWithWhereWithoutResourcesInput[]
  deleteMany?: Prisma.working_hoursScalarWhereInput | Prisma.working_hoursScalarWhereInput[]
}

export type working_hoursCreateWithoutResourcesInput = {
  weekday: number
  start_time: Date | string
  end_time: Date | string
}

export type working_hoursUncheckedCreateWithoutResourcesInput = {
  id?: number
  weekday: number
  start_time: Date | string
  end_time: Date | string
}

export type working_hoursCreateOrConnectWithoutResourcesInput = {
  where: Prisma.working_hoursWhereUniqueInput
  create: Prisma.XOR<Prisma.working_hoursCreateWithoutResourcesInput, Prisma.working_hoursUncheckedCreateWithoutResourcesInput>
}

export type working_hoursCreateManyResourcesInputEnvelope = {
  data: Prisma.working_hoursCreateManyResourcesInput | Prisma.working_hoursCreateManyResourcesInput[]
  skipDuplicates?: boolean
}

export type working_hoursUpsertWithWhereUniqueWithoutResourcesInput = {
  where: Prisma.working_hoursWhereUniqueInput
  update: Prisma.XOR<Prisma.working_hoursUpdateWithoutResourcesInput, Prisma.working_hoursUncheckedUpdateWithoutResourcesInput>
  create: Prisma.XOR<Prisma.working_hoursCreateWithoutResourcesInput, Prisma.working_hoursUncheckedCreateWithoutResourcesInput>
}

export type working_hoursUpdateWithWhereUniqueWithoutResourcesInput = {
  where: Prisma.working_hoursWhereUniqueInput
  data: Prisma.XOR<Prisma.working_hoursUpdateWithoutResourcesInput, Prisma.working_hoursUncheckedUpdateWithoutResourcesInput>
}

export type working_hoursUpdateManyWithWhereWithoutResourcesInput = {
  where: Prisma.working_hoursScalarWhereInput
  data: Prisma.XOR<Prisma.working_hoursUpdateManyMutationInput, Prisma.working_hoursUncheckedUpdateManyWithoutResourcesInput>
}

export type working_hoursScalarWhereInput = {
  AND?: Prisma.working_hoursScalarWhereInput | Prisma.working_hoursScalarWhereInput[]
  OR?: Prisma.working_hoursScalarWhereInput[]
  NOT?: Prisma.working_hoursScalarWhereInput | Prisma.working_hoursScalarWhereInput[]
  id?: Prisma.IntFilter<"working_hours"> | number
  resource_id?: Prisma.IntFilter<"working_hours"> | number
  weekday?: Prisma.IntFilter<"working_hours"> | number
  start_time?: Prisma.DateTimeFilter<"working_hours"> | Date | string
  end_time?: Prisma.DateTimeFilter<"working_hours"> | Date | string
}

export type working_hoursCreateManyResourcesInput = {
  id?: number
  weekday: number
  start_time: Date | string
  end_time: Date | string
}

export type working_hoursUpdateWithoutResourcesInput = {
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type working_hoursUncheckedUpdateWithoutResourcesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type working_hoursUncheckedUpdateManyWithoutResourcesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  weekday?: Prisma.IntFieldUpdateOperationsInput | number
  start_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  end_time?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type working_hoursSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  resource_id?: boolean
  weekday?: boolean
  start_time?: boolean
  end_time?: boolean
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["working_hours"]>

export type working_hoursSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  resource_id?: boolean
  weekday?: boolean
  start_time?: boolean
  end_time?: boolean
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["working_hours"]>

export type working_hoursSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  resource_id?: boolean
  weekday?: boolean
  start_time?: boolean
  end_time?: boolean
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["working_hours"]>

export type working_hoursSelectScalar = {
  id?: boolean
  resource_id?: boolean
  weekday?: boolean
  start_time?: boolean
  end_time?: boolean
}

export type working_hoursOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "resource_id" | "weekday" | "start_time" | "end_time", ExtArgs["result"]["working_hours"]>
export type working_hoursInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
}
export type working_hoursIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
}
export type working_hoursIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  resources?: boolean | Prisma.resourcesDefaultArgs<ExtArgs>
}

export type $working_hoursPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "working_hours"
  objects: {
    resources: Prisma.$resourcesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    resource_id: number
    weekday: number
    start_time: Date
    end_time: Date
  }, ExtArgs["result"]["working_hours"]>
  composites: {}
}

export type working_hoursGetPayload<S extends boolean | null | undefined | working_hoursDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$working_hoursPayload, S>

export type working_hoursCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<working_hoursFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Working_hoursCountAggregateInputType | true
  }

export interface working_hoursDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['working_hours'], meta: { name: 'working_hours' } }
  /**
   * Find zero or one Working_hours that matches the filter.
   * @param {working_hoursFindUniqueArgs} args - Arguments to find a Working_hours
   * @example
   * // Get one Working_hours
   * const working_hours = await prisma.working_hours.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends working_hoursFindUniqueArgs>(args: Prisma.SelectSubset<T, working_hoursFindUniqueArgs<ExtArgs>>): Prisma.Prisma__working_hoursClient<runtime.Types.Result.GetResult<Prisma.$working_hoursPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Working_hours that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {working_hoursFindUniqueOrThrowArgs} args - Arguments to find a Working_hours
   * @example
   * // Get one Working_hours
   * const working_hours = await prisma.working_hours.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends working_hoursFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, working_hoursFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__working_hoursClient<runtime.Types.Result.GetResult<Prisma.$working_hoursPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Working_hours that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {working_hoursFindFirstArgs} args - Arguments to find a Working_hours
   * @example
   * // Get one Working_hours
   * const working_hours = await prisma.working_hours.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends working_hoursFindFirstArgs>(args?: Prisma.SelectSubset<T, working_hoursFindFirstArgs<ExtArgs>>): Prisma.Prisma__working_hoursClient<runtime.Types.Result.GetResult<Prisma.$working_hoursPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Working_hours that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {working_hoursFindFirstOrThrowArgs} args - Arguments to find a Working_hours
   * @example
   * // Get one Working_hours
   * const working_hours = await prisma.working_hours.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends working_hoursFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, working_hoursFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__working_hoursClient<runtime.Types.Result.GetResult<Prisma.$working_hoursPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Working_hours that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {working_hoursFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Working_hours
   * const working_hours = await prisma.working_hours.findMany()
   * 
   * // Get first 10 Working_hours
   * const working_hours = await prisma.working_hours.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const working_hoursWithIdOnly = await prisma.working_hours.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends working_hoursFindManyArgs>(args?: Prisma.SelectSubset<T, working_hoursFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$working_hoursPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Working_hours.
   * @param {working_hoursCreateArgs} args - Arguments to create a Working_hours.
   * @example
   * // Create one Working_hours
   * const Working_hours = await prisma.working_hours.create({
   *   data: {
   *     // ... data to create a Working_hours
   *   }
   * })
   * 
   */
  create<T extends working_hoursCreateArgs>(args: Prisma.SelectSubset<T, working_hoursCreateArgs<ExtArgs>>): Prisma.Prisma__working_hoursClient<runtime.Types.Result.GetResult<Prisma.$working_hoursPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Working_hours.
   * @param {working_hoursCreateManyArgs} args - Arguments to create many Working_hours.
   * @example
   * // Create many Working_hours
   * const working_hours = await prisma.working_hours.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends working_hoursCreateManyArgs>(args?: Prisma.SelectSubset<T, working_hoursCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Working_hours and returns the data saved in the database.
   * @param {working_hoursCreateManyAndReturnArgs} args - Arguments to create many Working_hours.
   * @example
   * // Create many Working_hours
   * const working_hours = await prisma.working_hours.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Working_hours and only return the `id`
   * const working_hoursWithIdOnly = await prisma.working_hours.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends working_hoursCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, working_hoursCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$working_hoursPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Working_hours.
   * @param {working_hoursDeleteArgs} args - Arguments to delete one Working_hours.
   * @example
   * // Delete one Working_hours
   * const Working_hours = await prisma.working_hours.delete({
   *   where: {
   *     // ... filter to delete one Working_hours
   *   }
   * })
   * 
   */
  delete<T extends working_hoursDeleteArgs>(args: Prisma.SelectSubset<T, working_hoursDeleteArgs<ExtArgs>>): Prisma.Prisma__working_hoursClient<runtime.Types.Result.GetResult<Prisma.$working_hoursPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Working_hours.
   * @param {working_hoursUpdateArgs} args - Arguments to update one Working_hours.
   * @example
   * // Update one Working_hours
   * const working_hours = await prisma.working_hours.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends working_hoursUpdateArgs>(args: Prisma.SelectSubset<T, working_hoursUpdateArgs<ExtArgs>>): Prisma.Prisma__working_hoursClient<runtime.Types.Result.GetResult<Prisma.$working_hoursPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Working_hours.
   * @param {working_hoursDeleteManyArgs} args - Arguments to filter Working_hours to delete.
   * @example
   * // Delete a few Working_hours
   * const { count } = await prisma.working_hours.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends working_hoursDeleteManyArgs>(args?: Prisma.SelectSubset<T, working_hoursDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Working_hours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {working_hoursUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Working_hours
   * const working_hours = await prisma.working_hours.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends working_hoursUpdateManyArgs>(args: Prisma.SelectSubset<T, working_hoursUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Working_hours and returns the data updated in the database.
   * @param {working_hoursUpdateManyAndReturnArgs} args - Arguments to update many Working_hours.
   * @example
   * // Update many Working_hours
   * const working_hours = await prisma.working_hours.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Working_hours and only return the `id`
   * const working_hoursWithIdOnly = await prisma.working_hours.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends working_hoursUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, working_hoursUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$working_hoursPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Working_hours.
   * @param {working_hoursUpsertArgs} args - Arguments to update or create a Working_hours.
   * @example
   * // Update or create a Working_hours
   * const working_hours = await prisma.working_hours.upsert({
   *   create: {
   *     // ... data to create a Working_hours
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Working_hours we want to update
   *   }
   * })
   */
  upsert<T extends working_hoursUpsertArgs>(args: Prisma.SelectSubset<T, working_hoursUpsertArgs<ExtArgs>>): Prisma.Prisma__working_hoursClient<runtime.Types.Result.GetResult<Prisma.$working_hoursPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Working_hours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {working_hoursCountArgs} args - Arguments to filter Working_hours to count.
   * @example
   * // Count the number of Working_hours
   * const count = await prisma.working_hours.count({
   *   where: {
   *     // ... the filter for the Working_hours we want to count
   *   }
   * })
  **/
  count<T extends working_hoursCountArgs>(
    args?: Prisma.Subset<T, working_hoursCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Working_hoursCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Working_hours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Working_hoursAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Working_hoursAggregateArgs>(args: Prisma.Subset<T, Working_hoursAggregateArgs>): Prisma.PrismaPromise<GetWorking_hoursAggregateType<T>>

  /**
   * Group by Working_hours.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {working_hoursGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends working_hoursGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: working_hoursGroupByArgs['orderBy'] }
      : { orderBy?: working_hoursGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, working_hoursGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorking_hoursGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the working_hours model
 */
readonly fields: working_hoursFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for working_hours.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__working_hoursClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  resources<T extends Prisma.resourcesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.resourcesDefaultArgs<ExtArgs>>): Prisma.Prisma__resourcesClient<runtime.Types.Result.GetResult<Prisma.$resourcesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the working_hours model
 */
export interface working_hoursFieldRefs {
  readonly id: Prisma.FieldRef<"working_hours", 'Int'>
  readonly resource_id: Prisma.FieldRef<"working_hours", 'Int'>
  readonly weekday: Prisma.FieldRef<"working_hours", 'Int'>
  readonly start_time: Prisma.FieldRef<"working_hours", 'DateTime'>
  readonly end_time: Prisma.FieldRef<"working_hours", 'DateTime'>
}
    

// Custom InputTypes
/**
 * working_hours findUnique
 */
export type working_hoursFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the working_hours
   */
  select?: Prisma.working_hoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the working_hours
   */
  omit?: Prisma.working_hoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.working_hoursInclude<ExtArgs> | null
  /**
   * Filter, which working_hours to fetch.
   */
  where: Prisma.working_hoursWhereUniqueInput
}

/**
 * working_hours findUniqueOrThrow
 */
export type working_hoursFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the working_hours
   */
  select?: Prisma.working_hoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the working_hours
   */
  omit?: Prisma.working_hoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.working_hoursInclude<ExtArgs> | null
  /**
   * Filter, which working_hours to fetch.
   */
  where: Prisma.working_hoursWhereUniqueInput
}

/**
 * working_hours findFirst
 */
export type working_hoursFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the working_hours
   */
  select?: Prisma.working_hoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the working_hours
   */
  omit?: Prisma.working_hoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.working_hoursInclude<ExtArgs> | null
  /**
   * Filter, which working_hours to fetch.
   */
  where?: Prisma.working_hoursWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of working_hours to fetch.
   */
  orderBy?: Prisma.working_hoursOrderByWithRelationInput | Prisma.working_hoursOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for working_hours.
   */
  cursor?: Prisma.working_hoursWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` working_hours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` working_hours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of working_hours.
   */
  distinct?: Prisma.Working_hoursScalarFieldEnum | Prisma.Working_hoursScalarFieldEnum[]
}

/**
 * working_hours findFirstOrThrow
 */
export type working_hoursFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the working_hours
   */
  select?: Prisma.working_hoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the working_hours
   */
  omit?: Prisma.working_hoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.working_hoursInclude<ExtArgs> | null
  /**
   * Filter, which working_hours to fetch.
   */
  where?: Prisma.working_hoursWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of working_hours to fetch.
   */
  orderBy?: Prisma.working_hoursOrderByWithRelationInput | Prisma.working_hoursOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for working_hours.
   */
  cursor?: Prisma.working_hoursWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` working_hours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` working_hours.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of working_hours.
   */
  distinct?: Prisma.Working_hoursScalarFieldEnum | Prisma.Working_hoursScalarFieldEnum[]
}

/**
 * working_hours findMany
 */
export type working_hoursFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the working_hours
   */
  select?: Prisma.working_hoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the working_hours
   */
  omit?: Prisma.working_hoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.working_hoursInclude<ExtArgs> | null
  /**
   * Filter, which working_hours to fetch.
   */
  where?: Prisma.working_hoursWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of working_hours to fetch.
   */
  orderBy?: Prisma.working_hoursOrderByWithRelationInput | Prisma.working_hoursOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing working_hours.
   */
  cursor?: Prisma.working_hoursWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` working_hours from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` working_hours.
   */
  skip?: number
  distinct?: Prisma.Working_hoursScalarFieldEnum | Prisma.Working_hoursScalarFieldEnum[]
}

/**
 * working_hours create
 */
export type working_hoursCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the working_hours
   */
  select?: Prisma.working_hoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the working_hours
   */
  omit?: Prisma.working_hoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.working_hoursInclude<ExtArgs> | null
  /**
   * The data needed to create a working_hours.
   */
  data: Prisma.XOR<Prisma.working_hoursCreateInput, Prisma.working_hoursUncheckedCreateInput>
}

/**
 * working_hours createMany
 */
export type working_hoursCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many working_hours.
   */
  data: Prisma.working_hoursCreateManyInput | Prisma.working_hoursCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * working_hours createManyAndReturn
 */
export type working_hoursCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the working_hours
   */
  select?: Prisma.working_hoursSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the working_hours
   */
  omit?: Prisma.working_hoursOmit<ExtArgs> | null
  /**
   * The data used to create many working_hours.
   */
  data: Prisma.working_hoursCreateManyInput | Prisma.working_hoursCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.working_hoursIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * working_hours update
 */
export type working_hoursUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the working_hours
   */
  select?: Prisma.working_hoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the working_hours
   */
  omit?: Prisma.working_hoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.working_hoursInclude<ExtArgs> | null
  /**
   * The data needed to update a working_hours.
   */
  data: Prisma.XOR<Prisma.working_hoursUpdateInput, Prisma.working_hoursUncheckedUpdateInput>
  /**
   * Choose, which working_hours to update.
   */
  where: Prisma.working_hoursWhereUniqueInput
}

/**
 * working_hours updateMany
 */
export type working_hoursUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update working_hours.
   */
  data: Prisma.XOR<Prisma.working_hoursUpdateManyMutationInput, Prisma.working_hoursUncheckedUpdateManyInput>
  /**
   * Filter which working_hours to update
   */
  where?: Prisma.working_hoursWhereInput
  /**
   * Limit how many working_hours to update.
   */
  limit?: number
}

/**
 * working_hours updateManyAndReturn
 */
export type working_hoursUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the working_hours
   */
  select?: Prisma.working_hoursSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the working_hours
   */
  omit?: Prisma.working_hoursOmit<ExtArgs> | null
  /**
   * The data used to update working_hours.
   */
  data: Prisma.XOR<Prisma.working_hoursUpdateManyMutationInput, Prisma.working_hoursUncheckedUpdateManyInput>
  /**
   * Filter which working_hours to update
   */
  where?: Prisma.working_hoursWhereInput
  /**
   * Limit how many working_hours to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.working_hoursIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * working_hours upsert
 */
export type working_hoursUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the working_hours
   */
  select?: Prisma.working_hoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the working_hours
   */
  omit?: Prisma.working_hoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.working_hoursInclude<ExtArgs> | null
  /**
   * The filter to search for the working_hours to update in case it exists.
   */
  where: Prisma.working_hoursWhereUniqueInput
  /**
   * In case the working_hours found by the `where` argument doesn't exist, create a new working_hours with this data.
   */
  create: Prisma.XOR<Prisma.working_hoursCreateInput, Prisma.working_hoursUncheckedCreateInput>
  /**
   * In case the working_hours was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.working_hoursUpdateInput, Prisma.working_hoursUncheckedUpdateInput>
}

/**
 * working_hours delete
 */
export type working_hoursDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the working_hours
   */
  select?: Prisma.working_hoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the working_hours
   */
  omit?: Prisma.working_hoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.working_hoursInclude<ExtArgs> | null
  /**
   * Filter which working_hours to delete.
   */
  where: Prisma.working_hoursWhereUniqueInput
}

/**
 * working_hours deleteMany
 */
export type working_hoursDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which working_hours to delete
   */
  where?: Prisma.working_hoursWhereInput
  /**
   * Limit how many working_hours to delete.
   */
  limit?: number
}

/**
 * working_hours without action
 */
export type working_hoursDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the working_hours
   */
  select?: Prisma.working_hoursSelect<ExtArgs> | null
  /**
   * Omit specific fields from the working_hours
   */
  omit?: Prisma.working_hoursOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.working_hoursInclude<ExtArgs> | null
}
