
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/library"
import type * as Prisma from "../models.js"
import { type PrismaClient } from "./class.js"

export type * from '../models.js'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
 * Metrics
 */
export type Metrics = runtime.Metrics
export type Metric<T> = runtime.Metric<T>
export type MetricHistogram = runtime.MetricHistogram
export type MetricHistogramBucket = runtime.MetricHistogramBucket

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
export const prismaVersion: PrismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  bookings: 'bookings',
  cart_items: 'cart_items',
  carts: 'carts',
  order_items: 'order_items',
  orders: 'orders',
  products: 'products',
  resource_services: 'resource_services',
  resources: 'resources',
  salon_services: 'salon_services',
  schedule_overrides: 'schedule_overrides',
  sessions: 'sessions',
  users: 'users',
  working_hours: 'working_hours'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "bookings" | "cart_items" | "carts" | "order_items" | "orders" | "products" | "resource_services" | "resources" | "salon_services" | "schedule_overrides" | "sessions" | "users" | "working_hours"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    bookings: {
      payload: Prisma.$bookingsPayload<ExtArgs>
      fields: Prisma.bookingsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.bookingsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookingsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.bookingsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookingsPayload>
        }
        findFirst: {
          args: Prisma.bookingsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookingsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.bookingsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookingsPayload>
        }
        findMany: {
          args: Prisma.bookingsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookingsPayload>[]
        }
        create: {
          args: Prisma.bookingsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookingsPayload>
        }
        createMany: {
          args: Prisma.bookingsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.bookingsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookingsPayload>[]
        }
        delete: {
          args: Prisma.bookingsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookingsPayload>
        }
        update: {
          args: Prisma.bookingsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookingsPayload>
        }
        deleteMany: {
          args: Prisma.bookingsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.bookingsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.bookingsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookingsPayload>[]
        }
        upsert: {
          args: Prisma.bookingsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$bookingsPayload>
        }
        aggregate: {
          args: Prisma.BookingsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBookings>
        }
        groupBy: {
          args: Prisma.bookingsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BookingsGroupByOutputType>[]
        }
        count: {
          args: Prisma.bookingsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BookingsCountAggregateOutputType> | number
        }
      }
    }
    cart_items: {
      payload: Prisma.$cart_itemsPayload<ExtArgs>
      fields: Prisma.cart_itemsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.cart_itemsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cart_itemsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.cart_itemsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cart_itemsPayload>
        }
        findFirst: {
          args: Prisma.cart_itemsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cart_itemsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.cart_itemsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cart_itemsPayload>
        }
        findMany: {
          args: Prisma.cart_itemsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cart_itemsPayload>[]
        }
        create: {
          args: Prisma.cart_itemsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cart_itemsPayload>
        }
        createMany: {
          args: Prisma.cart_itemsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.cart_itemsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cart_itemsPayload>[]
        }
        delete: {
          args: Prisma.cart_itemsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cart_itemsPayload>
        }
        update: {
          args: Prisma.cart_itemsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cart_itemsPayload>
        }
        deleteMany: {
          args: Prisma.cart_itemsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.cart_itemsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.cart_itemsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cart_itemsPayload>[]
        }
        upsert: {
          args: Prisma.cart_itemsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cart_itemsPayload>
        }
        aggregate: {
          args: Prisma.Cart_itemsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCart_items>
        }
        groupBy: {
          args: Prisma.cart_itemsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Cart_itemsGroupByOutputType>[]
        }
        count: {
          args: Prisma.cart_itemsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Cart_itemsCountAggregateOutputType> | number
        }
      }
    }
    carts: {
      payload: Prisma.$cartsPayload<ExtArgs>
      fields: Prisma.cartsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.cartsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cartsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.cartsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cartsPayload>
        }
        findFirst: {
          args: Prisma.cartsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cartsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.cartsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cartsPayload>
        }
        findMany: {
          args: Prisma.cartsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cartsPayload>[]
        }
        create: {
          args: Prisma.cartsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cartsPayload>
        }
        createMany: {
          args: Prisma.cartsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.cartsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cartsPayload>[]
        }
        delete: {
          args: Prisma.cartsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cartsPayload>
        }
        update: {
          args: Prisma.cartsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cartsPayload>
        }
        deleteMany: {
          args: Prisma.cartsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.cartsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.cartsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cartsPayload>[]
        }
        upsert: {
          args: Prisma.cartsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$cartsPayload>
        }
        aggregate: {
          args: Prisma.CartsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCarts>
        }
        groupBy: {
          args: Prisma.cartsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CartsGroupByOutputType>[]
        }
        count: {
          args: Prisma.cartsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CartsCountAggregateOutputType> | number
        }
      }
    }
    order_items: {
      payload: Prisma.$order_itemsPayload<ExtArgs>
      fields: Prisma.order_itemsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.order_itemsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_itemsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.order_itemsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_itemsPayload>
        }
        findFirst: {
          args: Prisma.order_itemsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_itemsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.order_itemsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_itemsPayload>
        }
        findMany: {
          args: Prisma.order_itemsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_itemsPayload>[]
        }
        create: {
          args: Prisma.order_itemsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_itemsPayload>
        }
        createMany: {
          args: Prisma.order_itemsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.order_itemsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_itemsPayload>[]
        }
        delete: {
          args: Prisma.order_itemsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_itemsPayload>
        }
        update: {
          args: Prisma.order_itemsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_itemsPayload>
        }
        deleteMany: {
          args: Prisma.order_itemsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.order_itemsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.order_itemsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_itemsPayload>[]
        }
        upsert: {
          args: Prisma.order_itemsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$order_itemsPayload>
        }
        aggregate: {
          args: Prisma.Order_itemsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateOrder_items>
        }
        groupBy: {
          args: Prisma.order_itemsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Order_itemsGroupByOutputType>[]
        }
        count: {
          args: Prisma.order_itemsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Order_itemsCountAggregateOutputType> | number
        }
      }
    }
    orders: {
      payload: Prisma.$ordersPayload<ExtArgs>
      fields: Prisma.ordersFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ordersFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ordersPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ordersFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ordersPayload>
        }
        findFirst: {
          args: Prisma.ordersFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ordersPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ordersFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ordersPayload>
        }
        findMany: {
          args: Prisma.ordersFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ordersPayload>[]
        }
        create: {
          args: Prisma.ordersCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ordersPayload>
        }
        createMany: {
          args: Prisma.ordersCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ordersCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ordersPayload>[]
        }
        delete: {
          args: Prisma.ordersDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ordersPayload>
        }
        update: {
          args: Prisma.ordersUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ordersPayload>
        }
        deleteMany: {
          args: Prisma.ordersDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ordersUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ordersUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ordersPayload>[]
        }
        upsert: {
          args: Prisma.ordersUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ordersPayload>
        }
        aggregate: {
          args: Prisma.OrdersAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateOrders>
        }
        groupBy: {
          args: Prisma.ordersGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.OrdersGroupByOutputType>[]
        }
        count: {
          args: Prisma.ordersCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.OrdersCountAggregateOutputType> | number
        }
      }
    }
    products: {
      payload: Prisma.$productsPayload<ExtArgs>
      fields: Prisma.productsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.productsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$productsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.productsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$productsPayload>
        }
        findFirst: {
          args: Prisma.productsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$productsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.productsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$productsPayload>
        }
        findMany: {
          args: Prisma.productsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$productsPayload>[]
        }
        create: {
          args: Prisma.productsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$productsPayload>
        }
        createMany: {
          args: Prisma.productsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.productsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$productsPayload>[]
        }
        delete: {
          args: Prisma.productsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$productsPayload>
        }
        update: {
          args: Prisma.productsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$productsPayload>
        }
        deleteMany: {
          args: Prisma.productsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.productsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.productsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$productsPayload>[]
        }
        upsert: {
          args: Prisma.productsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$productsPayload>
        }
        aggregate: {
          args: Prisma.ProductsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProducts>
        }
        groupBy: {
          args: Prisma.productsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductsGroupByOutputType>[]
        }
        count: {
          args: Prisma.productsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductsCountAggregateOutputType> | number
        }
      }
    }
    resource_services: {
      payload: Prisma.$resource_servicesPayload<ExtArgs>
      fields: Prisma.resource_servicesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.resource_servicesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resource_servicesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.resource_servicesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resource_servicesPayload>
        }
        findFirst: {
          args: Prisma.resource_servicesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resource_servicesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.resource_servicesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resource_servicesPayload>
        }
        findMany: {
          args: Prisma.resource_servicesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resource_servicesPayload>[]
        }
        create: {
          args: Prisma.resource_servicesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resource_servicesPayload>
        }
        createMany: {
          args: Prisma.resource_servicesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.resource_servicesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resource_servicesPayload>[]
        }
        delete: {
          args: Prisma.resource_servicesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resource_servicesPayload>
        }
        update: {
          args: Prisma.resource_servicesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resource_servicesPayload>
        }
        deleteMany: {
          args: Prisma.resource_servicesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.resource_servicesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.resource_servicesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resource_servicesPayload>[]
        }
        upsert: {
          args: Prisma.resource_servicesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resource_servicesPayload>
        }
        aggregate: {
          args: Prisma.Resource_servicesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateResource_services>
        }
        groupBy: {
          args: Prisma.resource_servicesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Resource_servicesGroupByOutputType>[]
        }
        count: {
          args: Prisma.resource_servicesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Resource_servicesCountAggregateOutputType> | number
        }
      }
    }
    resources: {
      payload: Prisma.$resourcesPayload<ExtArgs>
      fields: Prisma.resourcesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.resourcesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resourcesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.resourcesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resourcesPayload>
        }
        findFirst: {
          args: Prisma.resourcesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resourcesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.resourcesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resourcesPayload>
        }
        findMany: {
          args: Prisma.resourcesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resourcesPayload>[]
        }
        create: {
          args: Prisma.resourcesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resourcesPayload>
        }
        createMany: {
          args: Prisma.resourcesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.resourcesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resourcesPayload>[]
        }
        delete: {
          args: Prisma.resourcesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resourcesPayload>
        }
        update: {
          args: Prisma.resourcesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resourcesPayload>
        }
        deleteMany: {
          args: Prisma.resourcesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.resourcesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.resourcesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resourcesPayload>[]
        }
        upsert: {
          args: Prisma.resourcesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$resourcesPayload>
        }
        aggregate: {
          args: Prisma.ResourcesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateResources>
        }
        groupBy: {
          args: Prisma.resourcesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ResourcesGroupByOutputType>[]
        }
        count: {
          args: Prisma.resourcesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ResourcesCountAggregateOutputType> | number
        }
      }
    }
    salon_services: {
      payload: Prisma.$salon_servicesPayload<ExtArgs>
      fields: Prisma.salon_servicesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.salon_servicesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$salon_servicesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.salon_servicesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$salon_servicesPayload>
        }
        findFirst: {
          args: Prisma.salon_servicesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$salon_servicesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.salon_servicesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$salon_servicesPayload>
        }
        findMany: {
          args: Prisma.salon_servicesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$salon_servicesPayload>[]
        }
        delete: {
          args: Prisma.salon_servicesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$salon_servicesPayload>
        }
        update: {
          args: Prisma.salon_servicesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$salon_servicesPayload>
        }
        deleteMany: {
          args: Prisma.salon_servicesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.salon_servicesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.salon_servicesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$salon_servicesPayload>[]
        }
        aggregate: {
          args: Prisma.Salon_servicesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSalon_services>
        }
        groupBy: {
          args: Prisma.salon_servicesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Salon_servicesGroupByOutputType>[]
        }
        count: {
          args: Prisma.salon_servicesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Salon_servicesCountAggregateOutputType> | number
        }
      }
    }
    schedule_overrides: {
      payload: Prisma.$schedule_overridesPayload<ExtArgs>
      fields: Prisma.schedule_overridesFieldRefs
      operations: {
        findUnique: {
          args: Prisma.schedule_overridesFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$schedule_overridesPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.schedule_overridesFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$schedule_overridesPayload>
        }
        findFirst: {
          args: Prisma.schedule_overridesFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$schedule_overridesPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.schedule_overridesFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$schedule_overridesPayload>
        }
        findMany: {
          args: Prisma.schedule_overridesFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$schedule_overridesPayload>[]
        }
        create: {
          args: Prisma.schedule_overridesCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$schedule_overridesPayload>
        }
        createMany: {
          args: Prisma.schedule_overridesCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.schedule_overridesCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$schedule_overridesPayload>[]
        }
        delete: {
          args: Prisma.schedule_overridesDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$schedule_overridesPayload>
        }
        update: {
          args: Prisma.schedule_overridesUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$schedule_overridesPayload>
        }
        deleteMany: {
          args: Prisma.schedule_overridesDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.schedule_overridesUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.schedule_overridesUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$schedule_overridesPayload>[]
        }
        upsert: {
          args: Prisma.schedule_overridesUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$schedule_overridesPayload>
        }
        aggregate: {
          args: Prisma.Schedule_overridesAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSchedule_overrides>
        }
        groupBy: {
          args: Prisma.schedule_overridesGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Schedule_overridesGroupByOutputType>[]
        }
        count: {
          args: Prisma.schedule_overridesCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Schedule_overridesCountAggregateOutputType> | number
        }
      }
    }
    sessions: {
      payload: Prisma.$sessionsPayload<ExtArgs>
      fields: Prisma.sessionsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.sessionsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.sessionsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionsPayload>
        }
        findFirst: {
          args: Prisma.sessionsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.sessionsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionsPayload>
        }
        findMany: {
          args: Prisma.sessionsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionsPayload>[]
        }
        create: {
          args: Prisma.sessionsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionsPayload>
        }
        createMany: {
          args: Prisma.sessionsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.sessionsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionsPayload>[]
        }
        delete: {
          args: Prisma.sessionsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionsPayload>
        }
        update: {
          args: Prisma.sessionsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionsPayload>
        }
        deleteMany: {
          args: Prisma.sessionsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.sessionsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.sessionsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionsPayload>[]
        }
        upsert: {
          args: Prisma.sessionsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$sessionsPayload>
        }
        aggregate: {
          args: Prisma.SessionsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSessions>
        }
        groupBy: {
          args: Prisma.sessionsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SessionsGroupByOutputType>[]
        }
        count: {
          args: Prisma.sessionsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SessionsCountAggregateOutputType> | number
        }
      }
    }
    users: {
      payload: Prisma.$usersPayload<ExtArgs>
      fields: Prisma.usersFieldRefs
      operations: {
        findUnique: {
          args: Prisma.usersFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.usersFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>
        }
        findFirst: {
          args: Prisma.usersFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.usersFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>
        }
        findMany: {
          args: Prisma.usersFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>[]
        }
        create: {
          args: Prisma.usersCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>
        }
        createMany: {
          args: Prisma.usersCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.usersCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>[]
        }
        delete: {
          args: Prisma.usersDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>
        }
        update: {
          args: Prisma.usersUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>
        }
        deleteMany: {
          args: Prisma.usersDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.usersUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.usersUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>[]
        }
        upsert: {
          args: Prisma.usersUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$usersPayload>
        }
        aggregate: {
          args: Prisma.UsersAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUsers>
        }
        groupBy: {
          args: Prisma.usersGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsersGroupByOutputType>[]
        }
        count: {
          args: Prisma.usersCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsersCountAggregateOutputType> | number
        }
      }
    }
    working_hours: {
      payload: Prisma.$working_hoursPayload<ExtArgs>
      fields: Prisma.working_hoursFieldRefs
      operations: {
        findUnique: {
          args: Prisma.working_hoursFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$working_hoursPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.working_hoursFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$working_hoursPayload>
        }
        findFirst: {
          args: Prisma.working_hoursFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$working_hoursPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.working_hoursFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$working_hoursPayload>
        }
        findMany: {
          args: Prisma.working_hoursFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$working_hoursPayload>[]
        }
        create: {
          args: Prisma.working_hoursCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$working_hoursPayload>
        }
        createMany: {
          args: Prisma.working_hoursCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.working_hoursCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$working_hoursPayload>[]
        }
        delete: {
          args: Prisma.working_hoursDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$working_hoursPayload>
        }
        update: {
          args: Prisma.working_hoursUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$working_hoursPayload>
        }
        deleteMany: {
          args: Prisma.working_hoursDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.working_hoursUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.working_hoursUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$working_hoursPayload>[]
        }
        upsert: {
          args: Prisma.working_hoursUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$working_hoursPayload>
        }
        aggregate: {
          args: Prisma.Working_hoursAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateWorking_hours>
        }
        groupBy: {
          args: Prisma.working_hoursGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Working_hoursGroupByOutputType>[]
        }
        count: {
          args: Prisma.working_hoursCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Working_hoursCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const BookingsScalarFieldEnum = {
  id: 'id',
  resource_id: 'resource_id',
  customer_name: 'customer_name',
  customer_phone: 'customer_phone',
  customer_email: 'customer_email',
  start_time: 'start_time',
  end_time: 'end_time',
  status: 'status',
  service_id: 'service_id',
  created_at: 'created_at'
} as const

export type BookingsScalarFieldEnum = (typeof BookingsScalarFieldEnum)[keyof typeof BookingsScalarFieldEnum]


export const Cart_itemsScalarFieldEnum = {
  id: 'id',
  cart_id: 'cart_id',
  product_id: 'product_id',
  quantity: 'quantity'
} as const

export type Cart_itemsScalarFieldEnum = (typeof Cart_itemsScalarFieldEnum)[keyof typeof Cart_itemsScalarFieldEnum]


export const CartsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  updated_at: 'updated_at'
} as const

export type CartsScalarFieldEnum = (typeof CartsScalarFieldEnum)[keyof typeof CartsScalarFieldEnum]


export const Order_itemsScalarFieldEnum = {
  id: 'id',
  order_id: 'order_id',
  product_id: 'product_id',
  price_at_purchase: 'price_at_purchase',
  quantity: 'quantity'
} as const

export type Order_itemsScalarFieldEnum = (typeof Order_itemsScalarFieldEnum)[keyof typeof Order_itemsScalarFieldEnum]


export const OrdersScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  total: 'total',
  status: 'status',
  created_at: 'created_at'
} as const

export type OrdersScalarFieldEnum = (typeof OrdersScalarFieldEnum)[keyof typeof OrdersScalarFieldEnum]


export const ProductsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  price: 'price',
  stock: 'stock',
  category: 'category'
} as const

export type ProductsScalarFieldEnum = (typeof ProductsScalarFieldEnum)[keyof typeof ProductsScalarFieldEnum]


export const Resource_servicesScalarFieldEnum = {
  resource_id: 'resource_id',
  service_id: 'service_id'
} as const

export type Resource_servicesScalarFieldEnum = (typeof Resource_servicesScalarFieldEnum)[keyof typeof Resource_servicesScalarFieldEnum]


export const ResourcesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  active: 'active'
} as const

export type ResourcesScalarFieldEnum = (typeof ResourcesScalarFieldEnum)[keyof typeof ResourcesScalarFieldEnum]


export const Salon_servicesScalarFieldEnum = {
  id: 'id',
  name: 'name',
  price: 'price',
  active: 'active'
} as const

export type Salon_servicesScalarFieldEnum = (typeof Salon_servicesScalarFieldEnum)[keyof typeof Salon_servicesScalarFieldEnum]


export const Schedule_overridesScalarFieldEnum = {
  id: 'id',
  resource_id: 'resource_id',
  date: 'date',
  working: 'working',
  start_time: 'start_time',
  end_time: 'end_time',
  note: 'note'
} as const

export type Schedule_overridesScalarFieldEnum = (typeof Schedule_overridesScalarFieldEnum)[keyof typeof Schedule_overridesScalarFieldEnum]


export const SessionsScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  token_hash: 'token_hash',
  expires_at: 'expires_at'
} as const

export type SessionsScalarFieldEnum = (typeof SessionsScalarFieldEnum)[keyof typeof SessionsScalarFieldEnum]


export const UsersScalarFieldEnum = {
  id: 'id',
  first_name: 'first_name',
  last_name: 'last_name',
  phone: 'phone',
  address: 'address',
  password_hash: 'password_hash',
  role: 'role'
} as const

export type UsersScalarFieldEnum = (typeof UsersScalarFieldEnum)[keyof typeof UsersScalarFieldEnum]


export const Working_hoursScalarFieldEnum = {
  id: 'id',
  resource_id: 'resource_id',
  weekday: 'weekday',
  start_time: 'start_time',
  end_time: 'end_time'
} as const

export type Working_hoursScalarFieldEnum = (typeof Working_hoursScalarFieldEnum)[keyof typeof Working_hoursScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'booking_status'
 */
export type Enumbooking_statusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'booking_status'>
    


/**
 * Reference to a field of type 'booking_status[]'
 */
export type ListEnumbooking_statusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'booking_status[]'>
    


/**
 * Reference to a field of type 'Decimal'
 */
export type DecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal'>
    


/**
 * Reference to a field of type 'Decimal[]'
 */
export type ListDecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'user_roles'
 */
export type Enumuser_rolesFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'user_roles'>
    


/**
 * Reference to a field of type 'user_roles[]'
 */
export type ListEnumuser_rolesFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'user_roles[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}


export type Datasource = {
  url?: string
}
export type Datasources = {
  db?: Datasource
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export interface PrismaClientOptions {
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasources?: Datasources
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasourceUrl?: string
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging#the-log-option).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-planetscale`
   */
  adapter?: runtime.SqlDriverAdapterFactory | null
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
}
export type GlobalOmitConfig = {
  bookings?: Prisma.bookingsOmit
  cart_items?: Prisma.cart_itemsOmit
  carts?: Prisma.cartsOmit
  order_items?: Prisma.order_itemsOmit
  orders?: Prisma.ordersOmit
  products?: Prisma.productsOmit
  resource_services?: Prisma.resource_servicesOmit
  resources?: Prisma.resourcesOmit
  salon_services?: Prisma.salon_servicesOmit
  schedule_overrides?: Prisma.schedule_overridesOmit
  sessions?: Prisma.sessionsOmit
  users?: Prisma.usersOmit
  working_hours?: Prisma.working_hoursOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

