
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 * 
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/library"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
export * from "./enums.js"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Bookings
 * const bookings = await prisma.bookings.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname)
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }


// file annotations for bundling tools to include these files
path.join(__dirname, "libquery_engine-debian-openssl-3.0.x.so.node")
path.join(process.cwd(), "prisma/..generated/prisma/libquery_engine-debian-openssl-3.0.x.so.node")

/**
 * Model bookings
 * 
 */
export type bookings = Prisma.bookingsModel
/**
 * Model cart_items
 * 
 */
export type cart_items = Prisma.cart_itemsModel
/**
 * Model carts
 * 
 */
export type carts = Prisma.cartsModel
/**
 * Model order_items
 * 
 */
export type order_items = Prisma.order_itemsModel
/**
 * Model orders
 * 
 */
export type orders = Prisma.ordersModel
/**
 * Model products
 * 
 */
export type products = Prisma.productsModel
/**
 * Model resource_services
 * 
 */
export type resource_services = Prisma.resource_servicesModel
/**
 * Model resources
 * 
 */
export type resources = Prisma.resourcesModel
/**
 * Model salon_services
 * 
 */
export type salon_services = Prisma.salon_servicesModel
/**
 * Model schedule_overrides
 * 
 */
export type schedule_overrides = Prisma.schedule_overridesModel
/**
 * Model sessions
 * 
 */
export type sessions = Prisma.sessionsModel
/**
 * Model users
 * 
 */
export type users = Prisma.usersModel
/**
 * Model working_hours
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 */
export type working_hours = Prisma.working_hoursModel
