
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const booking_status = {
  pending: 'pending',
  confirmed: 'confirmed',
  cancelled: 'cancelled',
  completed: 'completed'
} as const

export type booking_status = (typeof booking_status)[keyof typeof booking_status]


export const user_roles = {
  user: 'user',
  admin: 'admin',
  master: 'master'
} as const

export type user_roles = (typeof user_roles)[keyof typeof user_roles]
